In [126]:
import pandas as pd
import numpy as np

In [142]:
jde_data = pd.read_csv('jde_data-part1_raw.csv', sep=';', parse_dates=True)
jde_data

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0                1206810  2024-01-10 09:06:00.880            0            8   
1                1206809  2024-01-10 08:59:02.527            0            9   
2                1206808  2024-01-10 08:57:40.677            0            7   
3                1206807  2024-01-10 08:49:11.593            0            6   
4                1206806  2024-01-10 08:48:14.330            0            8   
...                  ...                      ...          ...          ...   
9995             1196814  2023-11-20 03:12:48.087          251           12   
9996             1196813  2023-11-20 03:09:00.397        505,1            7   
9997             1196812  2023-11-20 03:04:52.260        251,9           11   
9998             1196811  2023-11-20 03:00:06.253        505,9            6   
9999             1196810  2023-11-20 02:51:39.743        508,1            5   

      IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona SUMA_ZIELONEJ  \
0         138624        4000          0        NaN             0   
1         138623        3000          0        NaN             0   
2         138624        4000          0        NaN             0   
3         138624        4000          0        NaN         600,1   
4         138623        3000          0        NaN         400,3   
...          ...         ...        ...        ...           ...   
9995      137655        3000          0        NaN           300   
9996      137656        4000          0        NaN         600,1   
9997      137655        3000          0        NaN         291,1   
9998      137656        4000          0        NaN           600   
9999      137656        4000          0        NaN         600,2   

      QuantityError  ... im3_unit_name  ikWh_consumption  im3_consumption  \
0                 1  ...           NaN               NaN              NaN   
1                 1  ...           NaN               NaN              NaN   
2                 1  ...           NaN               NaN              NaN   
3                 1  ...            m3               4.0            474.0   
4                 1  ...            m3              23.0              8.0   
...             ...  ...           ...               ...              ...   
9995              0  ...            m3              13.0              9.0   
9996              0  ...            m3              11.0           1301.0   
9997              0  ...            m3              12.0              9.0   
9998              0  ...            m3              11.0           1307.0   
9999              0  ...            m3              12.0           1292.0   

      ikWh_counter1_start ikWh_counter1_finish  ikWh_multiplier1  \
0                     NaN                  NaN               NaN   
1                     NaN                  NaN               NaN   
2                     NaN                  NaN               NaN   
3              10921971.0           10922040.0              0,01   
4                     NaN                  NaN               NaN   
...                   ...                  ...               ...   
9995                  NaN                  NaN               NaN   
9996            9740934.0            9741095.0              0,01   
9997                  NaN                  NaN               NaN   
9998            9740751.0            9740900.0              0,01   
9999            9740431.0            9740653.0              0,01   

      ikWh_unit_name1  ikWh_consumption1  ikWh_total_consumption  \
0                 NaN                NaN                       0   
1                 NaN                NaN                       0   
2                 NaN                NaN                       0   
3                 kWh               0,69                    4,69   
4                 NaN                NaN                      23   
...               ...                ...                     ...   
9995              NaN 

In [143]:
jde_data.head()

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0             1206810  2024-01-10 09:06:00.880            0            8   
1             1206809  2024-01-10 08:59:02.527            0            9   
2             1206808  2024-01-10 08:57:40.677            0            7   
3             1206807  2024-01-10 08:49:11.593            0            6   
4             1206806  2024-01-10 08:48:14.330            0            8   

   IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona SUMA_ZIELONEJ  QuantityError  \
0      138624        4000          0        NaN             0              1   
1      138623        3000          0        NaN             0              1   
2      138624        4000          0        NaN             0              1   
3      138624        4000          0        NaN         600,1              1   
4      138623        3000          0        NaN         400,3              1   

   ... im3_unit_name  ikWh_consumption  im3_consumption  ikWh_counter1_start  \
0  ...           NaN               NaN              NaN                  NaN   
1  ...           NaN               NaN              NaN                  NaN   
2  ...           NaN               NaN              NaN                  NaN   
3  ...            m3               4.0            474.0           10921971.0   
4  ...            m3              23.0              8.0                  NaN   

  ikWh_counter1_finish  ikWh_multiplier1  ikWh_unit_name1  ikWh_consumption1  \
0                  NaN               NaN              NaN                NaN   
1                  NaN               NaN              NaN                NaN   
2                  NaN               NaN              NaN                NaN   
3           10922040.0              0,01              kWh               0,69   
4                  NaN               NaN              NaN                NaN   

   ikWh_total_consumption lTriggerCounter  
0                       0             NaN  
1                       0             NaN  
2                       0             NaN  
3                    4,69             NaN  
4                      23             NaN  

[5 rows x 38 columns]

In [144]:
jde_data['NUMERZASYPU'].unique()

array([ 8,  9,  7,  6,  5,  4,  3,  2,  1, 11, 10, 17, 16, 15, 14, 13, 12,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 51, 50,
       49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       52, 56, 55, 54, 53], dtype=int64)

In [145]:
jde_data['NUMERPIECA'].unique()

array([4000, 3000, 2000], dtype=int64)

In [146]:
jde_data['Anulowany'].unique()

array([0], dtype=int64)

In [147]:
jde_data.drop('Anulowany', axis=1, inplace=True)

In [148]:
jde_data['Zagubiona'].unique()

array([nan])

In [149]:
jde_data.drop('Zagubiona', axis=1, inplace=True)

In [150]:
jde_data

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0                1206810  2024-01-10 09:06:00.880            0            8   
1                1206809  2024-01-10 08:59:02.527            0            9   
2                1206808  2024-01-10 08:57:40.677            0            7   
3                1206807  2024-01-10 08:49:11.593            0            6   
4                1206806  2024-01-10 08:48:14.330            0            8   
...                  ...                      ...          ...          ...   
9995             1196814  2023-11-20 03:12:48.087          251           12   
9996             1196813  2023-11-20 03:09:00.397        505,1            7   
9997             1196812  2023-11-20 03:04:52.260        251,9           11   
9998             1196811  2023-11-20 03:00:06.253        505,9            6   
9999             1196810  2023-11-20 02:51:39.743        508,1            5   

      IDZLECENIE  NUMERPIECA SUMA_ZIELONEJ  QuantityError PREV_ILOSC_PALONA  \
0         138624        4000             0              1                 0   
1         138623        3000             0              1                 0   
2         138624        4000             0              1                 0   
3         138624        4000         600,1              1                 0   
4         138623        3000         400,3              1                 0   
...          ...         ...           ...            ...               ...   
9995      137655        3000           300              0               251   
9996      137656        4000         600,1              0             505,1   
9997      137655        3000         291,1              0             251,9   
9998      137656        4000           600              0             505,9   
9999      137656        4000         600,2              0             508,1   

      Posted  ...  im3_unit_name  ikWh_consumption im3_consumption  \
0          0  ...            NaN               NaN             NaN   
1          0  ...            NaN               NaN             NaN   
2          0  ...            NaN               NaN             NaN   
3          0  ...             m3               4.0           474.0   
4          0  ...             m3              23.0             8.0   
...      ...  ...            ...               ...             ...   
9995       1  ...             m3              13.0             9.0   
9996       1  ...             m3              11.0          1301.0   
9997       1  ...             m3              12.0             9.0   
9998       1  ...             m3              11.0          1307.0   
9999       1  ...             m3              12.0          1292.0   

      ikWh_counter1_start  ikWh_counter1_finish  ikWh_multiplier1  \
0                     NaN                   NaN               NaN   
1                     NaN                   NaN               NaN   
2                     NaN                   NaN               NaN   
3              10921971.0            10922040.0              0,01   
4                     NaN                   NaN               NaN   
...                   ...                   ...               ...   
9995                  NaN                   NaN               NaN   
9996            9740934.0             9741095.0              0,01   
9997                  NaN                   NaN               NaN   
9998            9740751.0             9740900.0              0,01   
9999            9740431.0             9740653.0              0,01   

      ikWh_unit_name1 ikWh_consumption1 ikWh_total_consumption  \
0                 NaN               NaN                      0   
1                 NaN               NaN                      0   
2                 NaN               NaN                      0   
3                 kWh              0,69                   4,69   
4                 NaN               NaN                     23   
...               ...               ...   

In [151]:
jde_data['ILOSC_PALONA'].equals(jde_data['PREV_ILOSC_PALONA'])

False

In [152]:
jde_data['ILOSC_PALONA'].eq(jde_data['PREV_ILOSC_PALONA'])

0       True
1       True
2       True
3       True
4       True
        ... 
9995    True
9996    True
9997    True
9998    True
9999    True
Length: 10000, dtype: bool

In [153]:
jde_data[jde_data['ILOSC_PALONA'] != jde_data['PREV_ILOSC_PALONA']] 

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
27               1206783  2024-01-10 05:48:18.430        342,1           11   
28               1206782  2024-01-10 05:39:07.180          343           10   
29               1206781  2024-01-10 05:31:45.677          343            9   
48               1206762  2024-01-10 03:49:24.690        347,8            9   
54               1206756  2024-01-10 03:23:50.053        348,8            6   
...                  ...                      ...          ...          ...   
9628             1197181  2023-11-21 20:05:44.993          338           11   
9702             1197107  2023-11-21 13:35:07.000          305            1   
9802             1197007  2023-11-21 02:28:07.180          300           16   
9886             1196923  2023-11-20 18:08:35.720          299            7   
9943             1196866  2023-11-20 07:55:31.313          501            5   

      IDZLECENIE  NUMERPIECA SUMA_ZIELONEJ  QuantityError PREV_ILOSC_PALONA  \
27        138620        3000         400,4              0               342   
28        138620        3000           401              0             342,7   
29        138620        3000         401,3              0             342,8   
48        138618        3000         400,9              0               348   
54        138618        3000         402,9              0               349   
...          ...         ...           ...            ...               ...   
9628      137692        3000         399,8              0             338,3   
9702      137684        3000         356,4              0             304,6   
9802      137673        3000         349,2              0             299,9   
9886      137667        3000         348,9              0             298,6   
9943      137660        4000      600,7001              0             501,3   

      Posted  ...  im3_unit_name  ikWh_consumption im3_consumption  \
27         0  ...             m3              15.0             8.0   
28         0  ...             m3              11.0             8.0   
29         0  ...             m3              15.0             9.0   
48         0  ...             m3              19.0             9.0   
54         0  ...             m3              17.0             8.0   
...      ...  ...            ...               ...             ...   
9628       0  ...             m3              18.0             9.0   
9702       0  ...             m3              10.0            10.0   
9802       0  ...             m3              13.0            10.0   
9886       0  ...             m3              14.0            10.0   
9943       0  ...             m3              11.0          1305.0   

      ikWh_counter1_start  ikWh_counter1_finish  ikWh_multiplier1  \
27                    NaN                   NaN               NaN   
28                    NaN                   NaN               NaN   
29                    NaN                   NaN               NaN   
48                    NaN                   NaN               NaN   
54                    NaN                   NaN               NaN   
...                   ...                   ...               ...   
9628                  NaN                   NaN               NaN   
9702                  NaN                   NaN               NaN   
9802                  NaN                   NaN               NaN   
9886                  NaN                   NaN               NaN   
9943            9749195.0             9749343.0              0,01   

      ikWh_unit_name1 ikWh_consumption1 ikWh_total_consumption  \
27                NaN               NaN                     15   
28                NaN               NaN                     11   
29                NaN               NaN                     15   
48                NaN               NaN                     19   
54                NaN               NaN                     17   
...               ...               ...   

In [154]:
jde_data.head()

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0             1206810  2024-01-10 09:06:00.880            0            8   
1             1206809  2024-01-10 08:59:02.527            0            9   
2             1206808  2024-01-10 08:57:40.677            0            7   
3             1206807  2024-01-10 08:49:11.593            0            6   
4             1206806  2024-01-10 08:48:14.330            0            8   

   IDZLECENIE  NUMERPIECA SUMA_ZIELONEJ  QuantityError PREV_ILOSC_PALONA  \
0      138624        4000             0              1                 0   
1      138623        3000             0              1                 0   
2      138624        4000             0              1                 0   
3      138624        4000         600,1              1                 0   
4      138623        3000         400,3              1                 0   

   Posted  ...  im3_unit_name  ikWh_consumption im3_consumption  \
0       0  ...            NaN               NaN             NaN   
1       0  ...            NaN               NaN             NaN   
2       0  ...            NaN               NaN             NaN   
3       0  ...             m3               4.0           474.0   
4       0  ...             m3              23.0             8.0   

   ikWh_counter1_start  ikWh_counter1_finish  ikWh_multiplier1  \
0                  NaN                   NaN               NaN   
1                  NaN                   NaN               NaN   
2                  NaN                   NaN               NaN   
3           10921971.0            10922040.0              0,01   
4                  NaN                   NaN               NaN   

   ikWh_unit_name1 ikWh_consumption1 ikWh_total_consumption  lTriggerCounter  
0              NaN               NaN                      0              NaN  
1              NaN               NaN                      0              NaN  
2              NaN               NaN                      0              NaN  
3              kWh              0,69                   4,69              NaN  
4              NaN               NaN                     23              NaN  

[5 rows x 36 columns]

In [155]:
jde_data['LockedByEditor'].unique()

array([nan,  0.])

In [156]:
jde_data[jde_data['LockedByEditor'] == 0.0]

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
7612             1199197  2023-11-30 06:28:11.693        306,8           19   

      IDZLECENIE  NUMERPIECA SUMA_ZIELONEJ  QuantityError PREV_ILOSC_PALONA  \
7612      137892        3000         352,6              0                 0   

      Posted  ...  im3_unit_name  ikWh_consumption im3_consumption  \
7612       0  ...             m3              13.0             8.0   

      ikWh_counter1_start  ikWh_counter1_finish  ikWh_multiplier1  \
7612                  NaN                   NaN               NaN   

      ikWh_unit_name1 ikWh_consumption1 ikWh_total_consumption  \
7612              NaN               NaN                     13   

      lTriggerCounter  
7612              NaN  

[1 rows x 36 columns]