In [255]:
import pandas as pd
import numpy as np

In [256]:
jde_data = pd.read_csv('jde_data-part1_raw.csv', sep=';', parse_dates=True)
jde_data

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0                1206810  2024-01-10 09:06:00.880            0            8   
1                1206809  2024-01-10 08:59:02.527            0            9   
2                1206808  2024-01-10 08:57:40.677            0            7   
3                1206807  2024-01-10 08:49:11.593            0            6   
4                1206806  2024-01-10 08:48:14.330            0            8   
...                  ...                      ...          ...          ...   
9995             1196814  2023-11-20 03:12:48.087          251           12   
9996             1196813  2023-11-20 03:09:00.397        505,1            7   
9997             1196812  2023-11-20 03:04:52.260        251,9           11   
9998             1196811  2023-11-20 03:00:06.253        505,9            6   
9999             1196810  2023-11-20 02:51:39.743        508,1            5   

      IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona SUMA_ZIELONEJ  \
0         138624        4000          0        NaN             0   
1         138623        3000          0        NaN             0   
2         138624        4000          0        NaN             0   
3         138624        4000          0        NaN         600,1   
4         138623        3000          0        NaN         400,3   
...          ...         ...        ...        ...           ...   
9995      137655        3000          0        NaN           300   
9996      137656        4000          0        NaN         600,1   
9997      137655        3000          0        NaN         291,1   
9998      137656        4000          0        NaN           600   
9999      137656        4000          0        NaN         600,2   

      QuantityError  ... im3_unit_name  ikWh_consumption  im3_consumption  \
0                 1  ...           NaN               NaN              NaN   
1                 1  ...           NaN               NaN              NaN   
2                 1  ...           NaN               NaN              NaN   
3                 1  ...            m3               4.0            474.0   
4                 1  ...            m3              23.0              8.0   
...             ...  ...           ...               ...              ...   
9995              0  ...            m3              13.0              9.0   
9996              0  ...            m3              11.0           1301.0   
9997              0  ...            m3              12.0              9.0   
9998              0  ...            m3              11.0           1307.0   
9999              0  ...            m3              12.0           1292.0   

      ikWh_counter1_start ikWh_counter1_finish  ikWh_multiplier1  \
0                     NaN                  NaN               NaN   
1                     NaN                  NaN               NaN   
2                     NaN                  NaN               NaN   
3              10921971.0           10922040.0              0,01   
4                     NaN                  NaN               NaN   
...                   ...                  ...               ...   
9995                  NaN                  NaN               NaN   
9996            9740934.0            9741095.0              0,01   
9997                  NaN                  NaN               NaN   
9998            9740751.0            9740900.0              0,01   
9999            9740431.0            9740653.0              0,01   

      ikWh_unit_name1  ikWh_consumption1  ikWh_total_consumption  \
0                 NaN                NaN                       0   
1                 NaN                NaN                       0   
2                 NaN                NaN                       0   
3                 kWh               0,69                    4,69   
4                 NaN                NaN                      23   
...               ...                ...                     ...   
9995              NaN 

In [257]:
jde_data.head()

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0             1206810  2024-01-10 09:06:00.880            0            8   
1             1206809  2024-01-10 08:59:02.527            0            9   
2             1206808  2024-01-10 08:57:40.677            0            7   
3             1206807  2024-01-10 08:49:11.593            0            6   
4             1206806  2024-01-10 08:48:14.330            0            8   

   IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona SUMA_ZIELONEJ  QuantityError  \
0      138624        4000          0        NaN             0              1   
1      138623        3000          0        NaN             0              1   
2      138624        4000          0        NaN             0              1   
3      138624        4000          0        NaN         600,1              1   
4      138623        3000          0        NaN         400,3              1   

   ... im3_unit_name  ikWh_consumption  im3_consumption  ikWh_counter1_start  \
0  ...           NaN               NaN              NaN                  NaN   
1  ...           NaN               NaN              NaN                  NaN   
2  ...           NaN               NaN              NaN                  NaN   
3  ...            m3               4.0            474.0           10921971.0   
4  ...            m3              23.0              8.0                  NaN   

  ikWh_counter1_finish  ikWh_multiplier1  ikWh_unit_name1  ikWh_consumption1  \
0                  NaN               NaN              NaN                NaN   
1                  NaN               NaN              NaN                NaN   
2                  NaN               NaN              NaN                NaN   
3           10922040.0              0,01              kWh               0,69   
4                  NaN               NaN              NaN                NaN   

   ikWh_total_consumption lTriggerCounter  
0                       0             NaN  
1                       0             NaN  
2                       0             NaN  
3                    4,69             NaN  
4                      23             NaN  

[5 rows x 38 columns]

In [258]:
jde_data['NUMERZASYPU'].unique()

array([ 8,  9,  7,  6,  5,  4,  3,  2,  1, 11, 10, 17, 16, 15, 14, 13, 12,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 51, 50,
       49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       52, 56, 55, 54, 53], dtype=int64)

In [259]:
jde_data['NUMERPIECA'].unique()

array([4000, 3000, 2000], dtype=int64)

In [260]:
jde_data['Anulowany'].unique()

array([0], dtype=int64)

In [261]:
jde_data.drop('Anulowany', axis=1, inplace=True)

In [262]:
jde_data['Zagubiona'].unique()

array([nan])

In [263]:
jde_data.drop('Zagubiona', axis=1, inplace=True)

In [264]:
jde_data

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0                1206810  2024-01-10 09:06:00.880            0            8   
1                1206809  2024-01-10 08:59:02.527            0            9   
2                1206808  2024-01-10 08:57:40.677            0            7   
3                1206807  2024-01-10 08:49:11.593            0            6   
4                1206806  2024-01-10 08:48:14.330            0            8   
...                  ...                      ...          ...          ...   
9995             1196814  2023-11-20 03:12:48.087          251           12   
9996             1196813  2023-11-20 03:09:00.397        505,1            7   
9997             1196812  2023-11-20 03:04:52.260        251,9           11   
9998             1196811  2023-11-20 03:00:06.253        505,9            6   
9999             1196810  2023-11-20 02:51:39.743        508,1            5   

      IDZLECENIE  NUMERPIECA SUMA_ZIELONEJ  QuantityError PREV_ILOSC_PALONA  \
0         138624        4000             0              1                 0   
1         138623        3000             0              1                 0   
2         138624        4000             0              1                 0   
3         138624        4000         600,1              1                 0   
4         138623        3000         400,3              1                 0   
...          ...         ...           ...            ...               ...   
9995      137655        3000           300              0               251   
9996      137656        4000         600,1              0             505,1   
9997      137655        3000         291,1              0             251,9   
9998      137656        4000           600              0             505,9   
9999      137656        4000         600,2              0             508,1   

      Posted  ...  im3_unit_name  ikWh_consumption im3_consumption  \
0          0  ...            NaN               NaN             NaN   
1          0  ...            NaN               NaN             NaN   
2          0  ...            NaN               NaN             NaN   
3          0  ...             m3               4.0           474.0   
4          0  ...             m3              23.0             8.0   
...      ...  ...            ...               ...             ...   
9995       1  ...             m3              13.0             9.0   
9996       1  ...             m3              11.0          1301.0   
9997       1  ...             m3              12.0             9.0   
9998       1  ...             m3              11.0          1307.0   
9999       1  ...             m3              12.0          1292.0   

      ikWh_counter1_start  ikWh_counter1_finish  ikWh_multiplier1  \
0                     NaN                   NaN               NaN   
1                     NaN                   NaN               NaN   
2                     NaN                   NaN               NaN   
3              10921971.0            10922040.0              0,01   
4                     NaN                   NaN               NaN   
...                   ...                   ...               ...   
9995                  NaN                   NaN               NaN   
9996            9740934.0             9741095.0              0,01   
9997                  NaN                   NaN               NaN   
9998            9740751.0             9740900.0              0,01   
9999            9740431.0             9740653.0              0,01   

      ikWh_unit_name1 ikWh_consumption1 ikWh_total_consumption  \
0                 NaN               NaN                      0   
1                 NaN               NaN                      0   
2                 NaN               NaN                      0   
3                 kWh              0,69                   4,69   
4                 NaN               NaN                     23   
...               ...               ...   

In [265]:
jde_data['ILOSC_PALONA'].equals(jde_data['PREV_ILOSC_PALONA'])

False

In [266]:
jde_data['ILOSC_PALONA'].eq(jde_data['PREV_ILOSC_PALONA'])

0       True
1       True
2       True
3       True
4       True
        ... 
9995    True
9996    True
9997    True
9998    True
9999    True
Length: 10000, dtype: bool

In [267]:
jde_data[jde_data['ILOSC_PALONA'] != jde_data['PREV_ILOSC_PALONA']]

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
27               1206783  2024-01-10 05:48:18.430        342,1           11   
28               1206782  2024-01-10 05:39:07.180          343           10   
29               1206781  2024-01-10 05:31:45.677          343            9   
48               1206762  2024-01-10 03:49:24.690        347,8            9   
54               1206756  2024-01-10 03:23:50.053        348,8            6   
...                  ...                      ...          ...          ...   
9628             1197181  2023-11-21 20:05:44.993          338           11   
9702             1197107  2023-11-21 13:35:07.000          305            1   
9802             1197007  2023-11-21 02:28:07.180          300           16   
9886             1196923  2023-11-20 18:08:35.720          299            7   
9943             1196866  2023-11-20 07:55:31.313          501            5   

      IDZLECENIE  NUMERPIECA SUMA_ZIELONEJ  QuantityError PREV_ILOSC_PALONA  \
27        138620        3000         400,4              0               342   
28        138620        3000           401              0             342,7   
29        138620        3000         401,3              0             342,8   
48        138618        3000         400,9              0               348   
54        138618        3000         402,9              0               349   
...          ...         ...           ...            ...               ...   
9628      137692        3000         399,8              0             338,3   
9702      137684        3000         356,4              0             304,6   
9802      137673        3000         349,2              0             299,9   
9886      137667        3000         348,9              0             298,6   
9943      137660        4000      600,7001              0             501,3   

      Posted  ...  im3_unit_name  ikWh_consumption im3_consumption  \
27         0  ...             m3              15.0             8.0   
28         0  ...             m3              11.0             8.0   
29         0  ...             m3              15.0             9.0   
48         0  ...             m3              19.0             9.0   
54         0  ...             m3              17.0             8.0   
...      ...  ...            ...               ...             ...   
9628       0  ...             m3              18.0             9.0   
9702       0  ...             m3              10.0            10.0   
9802       0  ...             m3              13.0            10.0   
9886       0  ...             m3              14.0            10.0   
9943       0  ...             m3              11.0          1305.0   

      ikWh_counter1_start  ikWh_counter1_finish  ikWh_multiplier1  \
27                    NaN                   NaN               NaN   
28                    NaN                   NaN               NaN   
29                    NaN                   NaN               NaN   
48                    NaN                   NaN               NaN   
54                    NaN                   NaN               NaN   
...                   ...                   ...               ...   
9628                  NaN                   NaN               NaN   
9702                  NaN                   NaN               NaN   
9802                  NaN                   NaN               NaN   
9886                  NaN                   NaN               NaN   
9943            9749195.0             9749343.0              0,01   

      ikWh_unit_name1 ikWh_consumption1 ikWh_total_consumption  \
27                NaN               NaN                     15   
28                NaN               NaN                     11   
29                NaN               NaN                     15   
48                NaN               NaN                     19   
54                NaN               NaN                     17   
...               ...               ...   

In [268]:
jde_data.head()

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0             1206810  2024-01-10 09:06:00.880            0            8   
1             1206809  2024-01-10 08:59:02.527            0            9   
2             1206808  2024-01-10 08:57:40.677            0            7   
3             1206807  2024-01-10 08:49:11.593            0            6   
4             1206806  2024-01-10 08:48:14.330            0            8   

   IDZLECENIE  NUMERPIECA SUMA_ZIELONEJ  QuantityError PREV_ILOSC_PALONA  \
0      138624        4000             0              1                 0   
1      138623        3000             0              1                 0   
2      138624        4000             0              1                 0   
3      138624        4000         600,1              1                 0   
4      138623        3000         400,3              1                 0   

   Posted  ...  im3_unit_name  ikWh_consumption im3_consumption  \
0       0  ...            NaN               NaN             NaN   
1       0  ...            NaN               NaN             NaN   
2       0  ...            NaN               NaN             NaN   
3       0  ...             m3               4.0           474.0   
4       0  ...             m3              23.0             8.0   

   ikWh_counter1_start  ikWh_counter1_finish  ikWh_multiplier1  \
0                  NaN                   NaN               NaN   
1                  NaN                   NaN               NaN   
2                  NaN                   NaN               NaN   
3           10921971.0            10922040.0              0,01   
4                  NaN                   NaN               NaN   

   ikWh_unit_name1 ikWh_consumption1 ikWh_total_consumption  lTriggerCounter  
0              NaN               NaN                      0              NaN  
1              NaN               NaN                      0              NaN  
2              NaN               NaN                      0              NaN  
3              kWh              0,69                   4,69              NaN  
4              NaN               NaN                     23              NaN  

[5 rows x 36 columns]

In [269]:
jde_data['LockedByEditor'].unique()

array([nan,  0.])

In [270]:
jde_data[jde_data['LockedByEditor'] == 0.0]

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
7612             1199197  2023-11-30 06:28:11.693        306,8           19   

      IDZLECENIE  NUMERPIECA SUMA_ZIELONEJ  QuantityError PREV_ILOSC_PALONA  \
7612      137892        3000         352,6              0                 0   

      Posted  ...  im3_unit_name  ikWh_consumption im3_consumption  \
7612       0  ...             m3              13.0             8.0   

      ikWh_counter1_start  ikWh_counter1_finish  ikWh_multiplier1  \
7612                  NaN                   NaN               NaN   

      ikWh_unit_name1 ikWh_consumption1 ikWh_total_consumption  \
7612              NaN               NaN                     13   

      lTriggerCounter  
7612              NaN  

[1 rows x 36 columns]

In [271]:
jde_data.drop('LockedByEditor', axis=1, inplace=True)

In [272]:
jde_data['QuantityError'].unique()

array([1, 0], dtype=int64)

In [273]:
jde_data[jde_data['QuantityError'] == 1]

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0             1206810  2024-01-10 09:06:00.880            0            8   
1             1206809  2024-01-10 08:59:02.527            0            9   
2             1206808  2024-01-10 08:57:40.677            0            7   
3             1206807  2024-01-10 08:49:11.593            0            6   
4             1206806  2024-01-10 08:48:14.330            0            8   
6             1206804  2024-01-10 08:35:09.410            0            5   

   IDZLECENIE  NUMERPIECA SUMA_ZIELONEJ  QuantityError PREV_ILOSC_PALONA  \
0      138624        4000             0              1                 0   
1      138623        3000             0              1                 0   
2      138624        4000             0              1                 0   
3      138624        4000         600,1              1                 0   
4      138623        3000         400,3              1                 0   
6      138624        4000         600,2              1                 0   

   Posted  ...  im3_unit_name ikWh_consumption  im3_consumption  \
0       0  ...            NaN              NaN              NaN   
1       0  ...            NaN              NaN              NaN   
2       0  ...            NaN              NaN              NaN   
3       0  ...             m3              4.0            474.0   
4       0  ...             m3             23.0              8.0   
6       0  ...             m3             11.0           1306.0   

   ikWh_counter1_start  ikWh_counter1_finish  ikWh_multiplier1  \
0                  NaN                   NaN               NaN   
1                  NaN                   NaN               NaN   
2                  NaN                   NaN               NaN   
3           10921971.0            10922040.0              0,01   
4                  NaN                   NaN               NaN   
6           10921766.0            10921965.0              0,01   

  ikWh_unit_name1 ikWh_consumption1  ikWh_total_consumption  lTriggerCounter  
0             NaN               NaN                       0              NaN  
1             NaN               NaN                       0              NaN  
2             NaN               NaN                       0              NaN  
3             kWh              0,69                    4,69              NaN  
4             NaN               NaN                      23              NaN  
6             kWh              1,99                   12,99              NaN  

[6 rows x 35 columns]

In [274]:
jde_data['Posted'].unique()

array([0, 1], dtype=int64)

In [275]:
jde_data[jde_data['Posted'] == 0]

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0                1206810  2024-01-10 09:06:00.880            0            8   
1                1206809  2024-01-10 08:59:02.527            0            9   
2                1206808  2024-01-10 08:57:40.677            0            7   
3                1206807  2024-01-10 08:49:11.593            0            6   
4                1206806  2024-01-10 08:48:14.330            0            8   
...                  ...                      ...          ...          ...   
9769             1197040  2023-11-21 05:11:49.350        511,5            4   
9771             1197038  2023-11-21 05:05:09.273        511,9            3   
9802             1197007  2023-11-21 02:28:07.180          300           16   
9886             1196923  2023-11-20 18:08:35.720          299            7   
9943             1196866  2023-11-20 07:55:31.313          501            5   

      IDZLECENIE  NUMERPIECA SUMA_ZIELONEJ  QuantityError PREV_ILOSC_PALONA  \
0         138624        4000             0              1                 0   
1         138623        3000             0              1                 0   
2         138624        4000             0              1                 0   
3         138624        4000         600,1              1                 0   
4         138623        3000         400,3              1                 0   
...          ...         ...           ...            ...               ...   
9769      137677        4000         600,4              0             511,5   
9771      137677        4000         600,3              0             511,9   
9802      137673        3000         349,2              0             299,9   
9886      137667        3000         348,9              0             298,6   
9943      137660        4000      600,7001              0             501,3   

      Posted  ...  im3_unit_name ikWh_consumption  im3_consumption  \
0          0  ...            NaN              NaN              NaN   
1          0  ...            NaN              NaN              NaN   
2          0  ...            NaN              NaN              NaN   
3          0  ...             m3              4.0            474.0   
4          0  ...             m3             23.0              8.0   
...      ...  ...            ...              ...              ...   
9769       0  ...             m3             10.0           1311.0   
9771       0  ...             m3              9.0           1322.0   
9802       0  ...             m3             13.0             10.0   
9886       0  ...             m3             14.0             10.0   
9943       0  ...             m3             11.0           1305.0   

      ikWh_counter1_start  ikWh_counter1_finish  ikWh_multiplier1  \
0                     NaN                   NaN               NaN   
1                     NaN                   NaN               NaN   
2                     NaN                   NaN               NaN   
3              10921971.0            10922040.0              0,01   
4                     NaN                   NaN               NaN   
...                   ...                   ...               ...   
9769            9773132.0             9773362.0              0,01   
9771            9772900.0             9773073.0              0,01   
9802                  NaN                   NaN               NaN   
9886                  NaN                   NaN               NaN   
9943            9749195.0             9749343.0              0,01   

     ikWh_unit_name1 ikWh_consumption1  ikWh_total_consumption  \
0                NaN               NaN                       0   
1                NaN               NaN                       0   
2                NaN               NaN                       0   
3                kWh              0,69                    4,69   
4                NaN               NaN                      23   
...              ...               ...    

In [276]:
jde_data.drop('dtLastEdited', axis=1, inplace=True)

In [277]:
jde_data

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0                1206810  2024-01-10 09:06:00.880            0            8   
1                1206809  2024-01-10 08:59:02.527            0            9   
2                1206808  2024-01-10 08:57:40.677            0            7   
3                1206807  2024-01-10 08:49:11.593            0            6   
4                1206806  2024-01-10 08:48:14.330            0            8   
...                  ...                      ...          ...          ...   
9995             1196814  2023-11-20 03:12:48.087          251           12   
9996             1196813  2023-11-20 03:09:00.397        505,1            7   
9997             1196812  2023-11-20 03:04:52.260        251,9           11   
9998             1196811  2023-11-20 03:00:06.253        505,9            6   
9999             1196810  2023-11-20 02:51:39.743        508,1            5   

      IDZLECENIE  NUMERPIECA SUMA_ZIELONEJ  QuantityError PREV_ILOSC_PALONA  \
0         138624        4000             0              1                 0   
1         138623        3000             0              1                 0   
2         138624        4000             0              1                 0   
3         138624        4000         600,1              1                 0   
4         138623        3000         400,3              1                 0   
...          ...         ...           ...            ...               ...   
9995      137655        3000           300              0               251   
9996      137656        4000         600,1              0             505,1   
9997      137655        3000         291,1              0             251,9   
9998      137656        4000           600              0             505,9   
9999      137656        4000         600,2              0             508,1   

      Posted  ...  im3_unit_name  ikWh_consumption  im3_consumption  \
0          0  ...            NaN               NaN              NaN   
1          0  ...            NaN               NaN              NaN   
2          0  ...            NaN               NaN              NaN   
3          0  ...             m3               4.0            474.0   
4          0  ...             m3              23.0              8.0   
...      ...  ...            ...               ...              ...   
9995       1  ...             m3              13.0              9.0   
9996       1  ...             m3              11.0           1301.0   
9997       1  ...             m3              12.0              9.0   
9998       1  ...             m3              11.0           1307.0   
9999       1  ...             m3              12.0           1292.0   

      ikWh_counter1_start  ikWh_counter1_finish ikWh_multiplier1  \
0                     NaN                   NaN              NaN   
1                     NaN                   NaN              NaN   
2                     NaN                   NaN              NaN   
3              10921971.0            10922040.0             0,01   
4                     NaN                   NaN              NaN   
...                   ...                   ...              ...   
9995                  NaN                   NaN              NaN   
9996            9740934.0             9741095.0             0,01   
9997                  NaN                   NaN              NaN   
9998            9740751.0             9740900.0             0,01   
9999            9740431.0             9740653.0             0,01   

     ikWh_unit_name1  ikWh_consumption1  ikWh_total_consumption  \
0                NaN                NaN                       0   
1                NaN                NaN                       0   
2                NaN                NaN                       0   
3                kWh               0,69                    4,69   
4                NaN                NaN                      23   
...              ...                

In [278]:
jde_data['ExternalErrorCleaner'].unique()

array([nan,  1.])

In [279]:
jde_data[jde_data['ExternalErrorCleaner'] == 1]

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
47               1206763  2024-01-10 03:51:05.300        519,3           10   
80               1206730  2024-01-10 01:00:30.273          345           32   
94               1206716  2024-01-09 23:55:07.663        504,6            5   
112              1206698  2024-01-09 22:37:56.997          346           13   
120              1206690  2024-01-09 22:03:15.270          348            9   
...                  ...                      ...          ...          ...   
9888             1196921  2023-11-20 18:01:44.660          310            6   
9890             1196919  2023-11-20 17:51:45.303          310            5   
9917             1196892  2023-11-20 11:20:35.740        427,3            3   
9977             1196832  2023-11-20 04:42:50.003          343            4   
9981             1196828  2023-11-20 04:25:17.787        342,7            2   

      IDZLECENIE  NUMERPIECA SUMA_ZIELONEJ  QuantityError PREV_ILOSC_PALONA  \
47        138619        4000         599,7              0             519,3   
80        138612        3000         400,1              0               345   
94        138615        4000         598,6              0             504,6   
112       138612        3000         400,2              0               346   
120       138612        3000         400,8              0               348   
...          ...         ...           ...            ...               ...   
9888      137667        3000         348,9              0               310   
9890      137667        3000         349,9              0               310   
9917      137662        4000         498,2              0             427,3   
9977      137658        3000         400,2              0               343   
9981      137658        3000         399,6              0             342,7   

      Posted  ...  im3_unit_name  ikWh_consumption  im3_consumption  \
47         1  ...             m3              10.0           1247.0   
80         1  ...             m3              16.0              8.0   
94         1  ...             m3              12.0           1237.0   
112        1  ...             m3              14.0              8.0   
120        1  ...             m3              17.0              9.0   
...      ...  ...            ...               ...              ...   
9888       1  ...             m3              12.0              9.0   
9890       1  ...             m3              12.0              9.0   
9917       1  ...             m3              10.0           1133.0   
9977       1  ...             m3              16.0             10.0   
9981       1  ...             m3              15.0             11.0   

      ikWh_counter1_start  ikWh_counter1_finish ikWh_multiplier1  \
47             10915660.0            10915792.0             0,01   
80                    NaN                   NaN              NaN   
94             10911737.0            10912046.0             0,01   
112                   NaN                   NaN              NaN   
120                   NaN                   NaN              NaN   
...                   ...                   ...              ...   
9888                  NaN                   NaN              NaN   
9890                  NaN                   NaN              NaN   
9917            9752768.0             9752894.0             0,01   
9977                  NaN                   NaN              NaN   
9981                  NaN                   NaN              NaN   

     ikWh_unit_name1  ikWh_consumption1  ikWh_total_consumption  \
47               kWh               1,32                   11,32   
80               NaN                NaN                      16   
94               kWh               3,09                   15,09   
112              NaN                NaN                      14   
120              NaN                NaN                      17   
...              ...                

In [280]:
jde_data.drop('ExternalErrorCleaner', axis=1, inplace=True)

In [281]:
jde_data

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0                1206810  2024-01-10 09:06:00.880            0            8   
1                1206809  2024-01-10 08:59:02.527            0            9   
2                1206808  2024-01-10 08:57:40.677            0            7   
3                1206807  2024-01-10 08:49:11.593            0            6   
4                1206806  2024-01-10 08:48:14.330            0            8   
...                  ...                      ...          ...          ...   
9995             1196814  2023-11-20 03:12:48.087          251           12   
9996             1196813  2023-11-20 03:09:00.397        505,1            7   
9997             1196812  2023-11-20 03:04:52.260        251,9           11   
9998             1196811  2023-11-20 03:00:06.253        505,9            6   
9999             1196810  2023-11-20 02:51:39.743        508,1            5   

      IDZLECENIE  NUMERPIECA SUMA_ZIELONEJ  QuantityError PREV_ILOSC_PALONA  \
0         138624        4000             0              1                 0   
1         138623        3000             0              1                 0   
2         138624        4000             0              1                 0   
3         138624        4000         600,1              1                 0   
4         138623        3000         400,3              1                 0   
...          ...         ...           ...            ...               ...   
9995      137655        3000           300              0               251   
9996      137656        4000         600,1              0             505,1   
9997      137655        3000         291,1              0             251,9   
9998      137656        4000           600              0             505,9   
9999      137656        4000         600,2              0             508,1   

      Posted  ...  im3_unit_name  ikWh_consumption  im3_consumption  \
0          0  ...            NaN               NaN              NaN   
1          0  ...            NaN               NaN              NaN   
2          0  ...            NaN               NaN              NaN   
3          0  ...             m3               4.0            474.0   
4          0  ...             m3              23.0              8.0   
...      ...  ...            ...               ...              ...   
9995       1  ...             m3              13.0              9.0   
9996       1  ...             m3              11.0           1301.0   
9997       1  ...             m3              12.0              9.0   
9998       1  ...             m3              11.0           1307.0   
9999       1  ...             m3              12.0           1292.0   

      ikWh_counter1_start ikWh_counter1_finish ikWh_multiplier1  \
0                     NaN                  NaN              NaN   
1                     NaN                  NaN              NaN   
2                     NaN                  NaN              NaN   
3              10921971.0           10922040.0             0,01   
4                     NaN                  NaN              NaN   
...                   ...                  ...              ...   
9995                  NaN                  NaN              NaN   
9996            9740934.0            9741095.0             0,01   
9997                  NaN                  NaN              NaN   
9998            9740751.0            9740900.0             0,01   
9999            9740431.0            9740653.0             0,01   

      ikWh_unit_name1  ikWh_consumption1  ikWh_total_consumption  \
0                 NaN                NaN                       0   
1                 NaN                NaN                       0   
2                 NaN                NaN                       0   
3                 kWh               0,69                    4,69   
4                 NaN                NaN                      23   
...               ...                ...  

In [282]:
jde_data['READJUSTED_BY'].unique()

array([nan, 24., 32., 40.,  6., 18., 10.])

In [283]:
jde_data.drop('READJUSTED_BY', axis=1, inplace=True)

In [284]:
jde_data

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0                1206810  2024-01-10 09:06:00.880            0            8   
1                1206809  2024-01-10 08:59:02.527            0            9   
2                1206808  2024-01-10 08:57:40.677            0            7   
3                1206807  2024-01-10 08:49:11.593            0            6   
4                1206806  2024-01-10 08:48:14.330            0            8   
...                  ...                      ...          ...          ...   
9995             1196814  2023-11-20 03:12:48.087          251           12   
9996             1196813  2023-11-20 03:09:00.397        505,1            7   
9997             1196812  2023-11-20 03:04:52.260        251,9           11   
9998             1196811  2023-11-20 03:00:06.253        505,9            6   
9999             1196810  2023-11-20 02:51:39.743        508,1            5   

      IDZLECENIE  NUMERPIECA SUMA_ZIELONEJ  QuantityError PREV_ILOSC_PALONA  \
0         138624        4000             0              1                 0   
1         138623        3000             0              1                 0   
2         138624        4000             0              1                 0   
3         138624        4000         600,1              1                 0   
4         138623        3000         400,3              1                 0   
...          ...         ...           ...            ...               ...   
9995      137655        3000           300              0               251   
9996      137656        4000         600,1              0             505,1   
9997      137655        3000         291,1              0             251,9   
9998      137656        4000           600              0             505,9   
9999      137656        4000         600,2              0             508,1   

      Posted  ...  im3_unit_name  ikWh_consumption  im3_consumption  \
0          0  ...            NaN               NaN              NaN   
1          0  ...            NaN               NaN              NaN   
2          0  ...            NaN               NaN              NaN   
3          0  ...             m3               4.0            474.0   
4          0  ...             m3              23.0              8.0   
...      ...  ...            ...               ...              ...   
9995       1  ...             m3              13.0              9.0   
9996       1  ...             m3              11.0           1301.0   
9997       1  ...             m3              12.0              9.0   
9998       1  ...             m3              11.0           1307.0   
9999       1  ...             m3              12.0           1292.0   

     ikWh_counter1_start ikWh_counter1_finish  ikWh_multiplier1  \
0                    NaN                  NaN               NaN   
1                    NaN                  NaN               NaN   
2                    NaN                  NaN               NaN   
3             10921971.0           10922040.0              0,01   
4                    NaN                  NaN               NaN   
...                  ...                  ...               ...   
9995                 NaN                  NaN               NaN   
9996           9740934.0            9741095.0              0,01   
9997                 NaN                  NaN               NaN   
9998           9740751.0            9740900.0              0,01   
9999           9740431.0            9740653.0              0,01   

      ikWh_unit_name1  ikWh_consumption1  ikWh_total_consumption  \
0                 NaN                NaN                       0   
1                 NaN                NaN                       0   
2                 NaN                NaN                       0   
3                 kWh               0,69                    4,69   
4                 NaN                NaN                      23   
...               ...                ...  

In [285]:
jde_data['TruckNo1'].unique()

array([ nan,   3., 204.,   5.,   7.,   1.,   9.,   8.,   6.,   4.,  10.,
        99., 202., 205.,   2.,  55.,  44.,  88.,  77.,  22., 200.])

In [286]:
jde_data.drop('TruckNo1', axis=1, inplace=True)

In [287]:
jde_data['TruckNo2'].unique()

array([nan])

In [288]:
jde_data.drop('TruckNo2', axis=1, inplace=True)

In [289]:
jde_data

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0                1206810  2024-01-10 09:06:00.880            0            8   
1                1206809  2024-01-10 08:59:02.527            0            9   
2                1206808  2024-01-10 08:57:40.677            0            7   
3                1206807  2024-01-10 08:49:11.593            0            6   
4                1206806  2024-01-10 08:48:14.330            0            8   
...                  ...                      ...          ...          ...   
9995             1196814  2023-11-20 03:12:48.087          251           12   
9996             1196813  2023-11-20 03:09:00.397        505,1            7   
9997             1196812  2023-11-20 03:04:52.260        251,9           11   
9998             1196811  2023-11-20 03:00:06.253        505,9            6   
9999             1196810  2023-11-20 02:51:39.743        508,1            5   

      IDZLECENIE  NUMERPIECA SUMA_ZIELONEJ  QuantityError PREV_ILOSC_PALONA  \
0         138624        4000             0              1                 0   
1         138623        3000             0              1                 0   
2         138624        4000             0              1                 0   
3         138624        4000         600,1              1                 0   
4         138623        3000         400,3              1                 0   
...          ...         ...           ...            ...               ...   
9995      137655        3000           300              0               251   
9996      137656        4000         600,1              0             505,1   
9997      137655        3000         291,1              0             251,9   
9998      137656        4000           600              0             505,9   
9999      137656        4000         600,2              0             508,1   

      Posted  ...  im3_unit_name ikWh_consumption im3_consumption  \
0          0  ...            NaN              NaN             NaN   
1          0  ...            NaN              NaN             NaN   
2          0  ...            NaN              NaN             NaN   
3          0  ...             m3              4.0           474.0   
4          0  ...             m3             23.0             8.0   
...      ...  ...            ...              ...             ...   
9995       1  ...             m3             13.0             9.0   
9996       1  ...             m3             11.0          1301.0   
9997       1  ...             m3             12.0             9.0   
9998       1  ...             m3             11.0          1307.0   
9999       1  ...             m3             12.0          1292.0   

      ikWh_counter1_start  ikWh_counter1_finish  ikWh_multiplier1  \
0                     NaN                   NaN               NaN   
1                     NaN                   NaN               NaN   
2                     NaN                   NaN               NaN   
3              10921971.0            10922040.0              0,01   
4                     NaN                   NaN               NaN   
...                   ...                   ...               ...   
9995                  NaN                   NaN               NaN   
9996            9740934.0             9741095.0              0,01   
9997                  NaN                   NaN               NaN   
9998            9740751.0             9740900.0              0,01   
9999            9740431.0             9740653.0              0,01   

      ikWh_unit_name1  ikWh_consumption1  ikWh_total_consumption  \
0                 NaN                NaN                       0   
1                 NaN                NaN                       0   
2                 NaN                NaN                       0   
3                 kWh               0,69                    4,69   
4                 NaN                NaN                      23   
...               ...                ...  

In [290]:
jde_data['lTriggerCounter'].unique()

array([  nan,  313.,  311., ..., 7144., 7143., 7142.])

In [291]:
jde_data.drop('lTriggerCounter', axis=1, inplace=True)

In [292]:
jde_data.drop('Posted', axis=1, inplace=True)

In [293]:
jde_data.drop('QuantityError', axis=1, inplace=True)

In [294]:
jde_data['im3_multiplier'].unique()

array([nan,  1.])

In [295]:
jde_data.drop('im3_multiplier', axis=1, inplace=True)

In [296]:
jde_data['ikWh_multiplier'].unique()

array([nan,  1.])

In [297]:
jde_data.drop('ikWh_multiplier', axis=1, inplace=True)

In [298]:
jde_data['ikWh_unit_name'].unique()

array([nan, 'kWh'], dtype=object)

In [299]:
jde_data.drop('ikWh_unit_name', axis=1, inplace=True)

In [300]:
jde_data['im3_unit_name'].unique()

array([nan, 'm3'], dtype=object)

In [301]:
jde_data['ikWh_multiplier1'].unique()

array([nan, '0,01'], dtype=object)

In [302]:
jde_data.drop('ikWh_multiplier1', axis=1, inplace=True)

In [303]:
jde_data.drop('im3_unit_name', axis=1, inplace=True)

In [306]:
jde_data['ikWh_unit_name1'].unique()

array([nan, 'kWh'], dtype=object)

In [308]:
jde_data.drop('ikWh_unit_name1', axis=1, inplace=True)

In [309]:
jde_data.rename(
    columns={'ID_ZLECENIA_PALONA': 'ID', 'DTZAPIS': 'Data zapisu', 'ILOSC_PALONA': 'Ilosc uprazonej kawy bez strat [kg]',
             'NUMERZASYPU': 'Numer zasypu', 'IDZLECENIE': 'ID zlecenia', 'NUMERPIECA': 'Numer Pieca',
             'SUMA_ZIELONEJ': 'Suma kawy wsypanej na poczatku prazenia [kg]',
             'ZbiornikKawyPalonej': 'Zbiornik kawy palonej', 'dtRoastingStart': 'Rozpoczecie procesu prazenia',
             'dtRoastingFinish': 'Zakonczenie procesu prazenia',
             'ikWh_counter_start': 'Stan licznika energii: poczatek prazenia [kWh]',
             'ikWh_counter_finish': 'Stan licznika energii: koniec prazenia [kWh]',
             'im3_counter_start': 'Stan licznika gazu: poczatek prazenia [m3]', 'im3_counter_finish' : 'Stan licznika gazu: koniec prazenia [m3]',  }, inplace=True)

In [310]:
jde_data

ID              Data zapisu Ilosc uprazonej kawy bez strat [kg]  \
0     1206810  2024-01-10 09:06:00.880                                   0   
1     1206809  2024-01-10 08:59:02.527                                   0   
2     1206808  2024-01-10 08:57:40.677                                   0   
3     1206807  2024-01-10 08:49:11.593                                   0   
4     1206806  2024-01-10 08:48:14.330                                   0   
...       ...                      ...                                 ...   
9995  1196814  2023-11-20 03:12:48.087                                 251   
9996  1196813  2023-11-20 03:09:00.397                               505,1   
9997  1196812  2023-11-20 03:04:52.260                               251,9   
9998  1196811  2023-11-20 03:00:06.253                               505,9   
9999  1196810  2023-11-20 02:51:39.743                               508,1   

      Numer zasypu  ID zlecenia  Numer Pieca  \
0                8       138624         4000   
1                9       138623         3000   
2                7       138624         4000   
3                6       138624         4000   
4                8       138623         3000   
...            ...          ...          ...   
9995            12       137655         3000   
9996             7       137656         4000   
9997            11       137655         3000   
9998             6       137656         4000   
9999             5       137656         4000   

     Suma kawy wsypanej na poczatku prazenia [kg] PREV_ILOSC_PALONA  \
0                                               0                 0   
1                                               0                 0   
2                                               0                 0   
3                                           600,1                 0   
4                                           400,3                 0   
...                                           ...               ...   
9995                                          300               251   
9996                                        600,1             505,1   
9997                                        291,1             251,9   
9998                                          600             505,9   
9999                                        600,2             508,1   

      Zbiornik kawy palonej Rozpoczecie procesu prazenia  ...  \
0                       639                          NaN  ...   
1                       654                          NaN  ...   
2                       639                          NaN  ...   
3                       639      2024-01-10 09:05:27.200  ...   
4                       654      2024-01-10 08:58:30.220  ...   
...                     ...                          ...  ...   
9995                    625      2023-11-20 03:18:51.253  ...   
9996                    652      2023-11-20 03:32:32.793  ...   
9997                    625      2023-11-20 03:11:40.280  ...   
9998                    652      2023-11-20 03:22:33.460  ...   
9999                    649      2023-11-20 03:08:12.943  ...   

     Stan licznika energii: poczatek prazenia [kWh]  \
0                                               NaN   
1                                               NaN   
2                                               NaN   
3                                         3858704.0   
4                                         1115853.0   
...                                             ...   
9995                                      1001316.0   
9996                                      3790029.0   
9997                                      1001300.0   
9998                                      3790016.0   
9999                                      3789999.0   

      Stan licznika energii: koniec prazenia [kWh]  \
0                                              NaN   
1                                              NaN   
2                                       