In [1]:
import pandas as pd
import numpy as np

C:\Users\modeb\AppData\Local\Temp\ipykernel_6980\2937650959.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
jde_data = pd.read_csv('jde_data-part1_raw.csv', sep=';', parse_dates=True)
jde_data

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0                1206810  2024-01-10 09:06:00.880            0            8   
1                1206809  2024-01-10 08:59:02.527            0            9   
2                1206808  2024-01-10 08:57:40.677            0            7   
3                1206807  2024-01-10 08:49:11.593            0            6   
4                1206806  2024-01-10 08:48:14.330            0            8   
...                  ...                      ...          ...          ...   
9995             1196814  2023-11-20 03:12:48.087          251           12   
9996             1196813  2023-11-20 03:09:00.397        505,1            7   
9997             1196812  2023-11-20 03:04:52.260        251,9           11   
9998             1196811  2023-11-20 03:00:06.253        505,9            6   
9999             1196810  2023-11-20 02:51:39.743        508,1            5   

      IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona SUMA_ZIELONEJ  \
0         138624        4000          0        NaN             0   
1         138623        3000          0        NaN             0   
2         138624        4000          0        NaN             0   
3         138624        4000          0        NaN         600,1   
4         138623        3000          0        NaN         400,3   
...          ...         ...        ...        ...           ...   
9995      137655        3000          0        NaN           300   
9996      137656        4000          0        NaN         600,1   
9997      137655        3000          0        NaN         291,1   
9998      137656        4000          0        NaN           600   
9999      137656        4000          0        NaN         600,2   

      QuantityError  ... im3_unit_name  ikWh_consumption  im3_consumption  \
0                 1  ...           NaN               NaN              NaN   
1                 1  ...           NaN               NaN              NaN   
2                 1  ...           NaN               NaN              NaN   
3                 1  ...            m3               4.0            474.0   
4                 1  ...            m3              23.0              8.0   
...             ...  ...           ...               ...              ...   
9995              0  ...            m3              13.0              9.0   
9996              0  ...            m3              11.0           1301.0   
9997              0  ...            m3              12.0              9.0   
9998              0  ...            m3              11.0           1307.0   
9999              0  ...            m3              12.0           1292.0   

      ikWh_counter1_start ikWh_counter1_finish  ikWh_multiplier1  \
0                     NaN                  NaN               NaN   
1                     NaN                  NaN               NaN   
2                     NaN                  NaN               NaN   
3              10921971.0           10922040.0              0,01   
4                     NaN                  NaN               NaN   
...                   ...                  ...               ...   
9995                  NaN                  NaN               NaN   
9996            9740934.0            9741095.0              0,01   
9997                  NaN                  NaN               NaN   
9998            9740751.0            9740900.0              0,01   
9999            9740431.0            9740653.0              0,01   

      ikWh_unit_name1  ikWh_consumption1  ikWh_total_consumption  \
0                 NaN                NaN                       0   
1                 NaN                NaN                       0   
2                 NaN                NaN                       0   
3                 kWh               0,69                    4,69   
4                 NaN                NaN                      23   
...               ...                ...                     ...   
9995              NaN 

In [3]:
columns_to_drop = []

In [4]:
jde_data.head()

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0             1206810  2024-01-10 09:06:00.880            0            8   
1             1206809  2024-01-10 08:59:02.527            0            9   
2             1206808  2024-01-10 08:57:40.677            0            7   
3             1206807  2024-01-10 08:49:11.593            0            6   
4             1206806  2024-01-10 08:48:14.330            0            8   

   IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona SUMA_ZIELONEJ  QuantityError  \
0      138624        4000          0        NaN             0              1   
1      138623        3000          0        NaN             0              1   
2      138624        4000          0        NaN             0              1   
3      138624        4000          0        NaN         600,1              1   
4      138623        3000          0        NaN         400,3              1   

   ... im3_unit_name  ikWh_consumption  im3_consumption  ikWh_counter1_start  \
0  ...           NaN               NaN              NaN                  NaN   
1  ...           NaN               NaN              NaN                  NaN   
2  ...           NaN               NaN              NaN                  NaN   
3  ...            m3               4.0            474.0           10921971.0   
4  ...            m3              23.0              8.0                  NaN   

  ikWh_counter1_finish  ikWh_multiplier1  ikWh_unit_name1  ikWh_consumption1  \
0                  NaN               NaN              NaN                NaN   
1                  NaN               NaN              NaN                NaN   
2                  NaN               NaN              NaN                NaN   
3           10922040.0              0,01              kWh               0,69   
4                  NaN               NaN              NaN                NaN   

   ikWh_total_consumption lTriggerCounter  
0                       0             NaN  
1                       0             NaN  
2                       0             NaN  
3                    4,69             NaN  
4                      23             NaN  

[5 rows x 38 columns]

In [5]:
jde_data['NUMERZASYPU'].unique()

array([ 8,  9,  7,  6,  5,  4,  3,  2,  1, 11, 10, 17, 16, 15, 14, 13, 12,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 51, 50,
       49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       52, 56, 55, 54, 53], dtype=int64)

In [6]:
jde_data['NUMERPIECA'].unique()

array([4000, 3000, 2000], dtype=int64)

In [7]:
jde_data['Anulowany'].unique()

array([0], dtype=int64)

In [8]:
columns_to_drop.append('Anulowany')

In [9]:
jde_data['Zagubiona'].unique()

array([nan])

In [10]:
columns_to_drop.append('Zagubiona')

In [11]:
jde_data

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0                1206810  2024-01-10 09:06:00.880            0            8   
1                1206809  2024-01-10 08:59:02.527            0            9   
2                1206808  2024-01-10 08:57:40.677            0            7   
3                1206807  2024-01-10 08:49:11.593            0            6   
4                1206806  2024-01-10 08:48:14.330            0            8   
...                  ...                      ...          ...          ...   
9995             1196814  2023-11-20 03:12:48.087          251           12   
9996             1196813  2023-11-20 03:09:00.397        505,1            7   
9997             1196812  2023-11-20 03:04:52.260        251,9           11   
9998             1196811  2023-11-20 03:00:06.253        505,9            6   
9999             1196810  2023-11-20 02:51:39.743        508,1            5   

      IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona SUMA_ZIELONEJ  \
0         138624        4000          0        NaN             0   
1         138623        3000          0        NaN             0   
2         138624        4000          0        NaN             0   
3         138624        4000          0        NaN         600,1   
4         138623        3000          0        NaN         400,3   
...          ...         ...        ...        ...           ...   
9995      137655        3000          0        NaN           300   
9996      137656        4000          0        NaN         600,1   
9997      137655        3000          0        NaN         291,1   
9998      137656        4000          0        NaN           600   
9999      137656        4000          0        NaN         600,2   

      QuantityError  ... im3_unit_name  ikWh_consumption  im3_consumption  \
0                 1  ...           NaN               NaN              NaN   
1                 1  ...           NaN               NaN              NaN   
2                 1  ...           NaN               NaN              NaN   
3                 1  ...            m3               4.0            474.0   
4                 1  ...            m3              23.0              8.0   
...             ...  ...           ...               ...              ...   
9995              0  ...            m3              13.0              9.0   
9996              0  ...            m3              11.0           1301.0   
9997              0  ...            m3              12.0              9.0   
9998              0  ...            m3              11.0           1307.0   
9999              0  ...            m3              12.0           1292.0   

      ikWh_counter1_start ikWh_counter1_finish  ikWh_multiplier1  \
0                     NaN                  NaN               NaN   
1                     NaN                  NaN               NaN   
2                     NaN                  NaN               NaN   
3              10921971.0           10922040.0              0,01   
4                     NaN                  NaN               NaN   
...                   ...                  ...               ...   
9995                  NaN                  NaN               NaN   
9996            9740934.0            9741095.0              0,01   
9997                  NaN                  NaN               NaN   
9998            9740751.0            9740900.0              0,01   
9999            9740431.0            9740653.0              0,01   

      ikWh_unit_name1  ikWh_consumption1  ikWh_total_consumption  \
0                 NaN                NaN                       0   
1                 NaN                NaN                       0   
2                 NaN                NaN                       0   
3                 kWh               0,69                    4,69   
4                 NaN                NaN                      23   
...               ...                ...                     ...   
9995              NaN 

In [12]:
jde_data['ILOSC_PALONA'].equals(jde_data['PREV_ILOSC_PALONA'])

False

In [13]:
jde_data['ILOSC_PALONA'].eq(jde_data['PREV_ILOSC_PALONA'])

0       True
1       True
2       True
3       True
4       True
        ... 
9995    True
9996    True
9997    True
9998    True
9999    True
Length: 10000, dtype: bool

In [14]:
jde_data[jde_data['ILOSC_PALONA'] != jde_data['PREV_ILOSC_PALONA']]

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
27               1206783  2024-01-10 05:48:18.430        342,1           11   
28               1206782  2024-01-10 05:39:07.180          343           10   
29               1206781  2024-01-10 05:31:45.677          343            9   
48               1206762  2024-01-10 03:49:24.690        347,8            9   
54               1206756  2024-01-10 03:23:50.053        348,8            6   
...                  ...                      ...          ...          ...   
9628             1197181  2023-11-21 20:05:44.993          338           11   
9702             1197107  2023-11-21 13:35:07.000          305            1   
9802             1197007  2023-11-21 02:28:07.180          300           16   
9886             1196923  2023-11-20 18:08:35.720          299            7   
9943             1196866  2023-11-20 07:55:31.313          501            5   

      IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona SUMA_ZIELONEJ  \
27        138620        3000          0        NaN         400,4   
28        138620        3000          0        NaN           401   
29        138620        3000          0        NaN         401,3   
48        138618        3000          0        NaN         400,9   
54        138618        3000          0        NaN         402,9   
...          ...         ...        ...        ...           ...   
9628      137692        3000          0        NaN         399,8   
9702      137684        3000          0        NaN         356,4   
9802      137673        3000          0        NaN         349,2   
9886      137667        3000          0        NaN         348,9   
9943      137660        4000          0        NaN      600,7001   

      QuantityError  ... im3_unit_name  ikWh_consumption  im3_consumption  \
27                0  ...            m3              15.0              8.0   
28                0  ...            m3              11.0              8.0   
29                0  ...            m3              15.0              9.0   
48                0  ...            m3              19.0              9.0   
54                0  ...            m3              17.0              8.0   
...             ...  ...           ...               ...              ...   
9628              0  ...            m3              18.0              9.0   
9702              0  ...            m3              10.0             10.0   
9802              0  ...            m3              13.0             10.0   
9886              0  ...            m3              14.0             10.0   
9943              0  ...            m3              11.0           1305.0   

      ikWh_counter1_start ikWh_counter1_finish  ikWh_multiplier1  \
27                    NaN                  NaN               NaN   
28                    NaN                  NaN               NaN   
29                    NaN                  NaN               NaN   
48                    NaN                  NaN               NaN   
54                    NaN                  NaN               NaN   
...                   ...                  ...               ...   
9628                  NaN                  NaN               NaN   
9702                  NaN                  NaN               NaN   
9802                  NaN                  NaN               NaN   
9886                  NaN                  NaN               NaN   
9943            9749195.0            9749343.0              0,01   

      ikWh_unit_name1  ikWh_consumption1  ikWh_total_consumption  \
27                NaN                NaN                      15   
28                NaN                NaN                      11   
29                NaN                NaN                      15   
48                NaN                NaN                      19   
54                NaN                NaN                      17   
...               ...                ...                     ...   
9628              NaN 

In [15]:
jde_data.head()

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0             1206810  2024-01-10 09:06:00.880            0            8   
1             1206809  2024-01-10 08:59:02.527            0            9   
2             1206808  2024-01-10 08:57:40.677            0            7   
3             1206807  2024-01-10 08:49:11.593            0            6   
4             1206806  2024-01-10 08:48:14.330            0            8   

   IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona SUMA_ZIELONEJ  QuantityError  \
0      138624        4000          0        NaN             0              1   
1      138623        3000          0        NaN             0              1   
2      138624        4000          0        NaN             0              1   
3      138624        4000          0        NaN         600,1              1   
4      138623        3000          0        NaN         400,3              1   

   ... im3_unit_name  ikWh_consumption  im3_consumption  ikWh_counter1_start  \
0  ...           NaN               NaN              NaN                  NaN   
1  ...           NaN               NaN              NaN                  NaN   
2  ...           NaN               NaN              NaN                  NaN   
3  ...            m3               4.0            474.0           10921971.0   
4  ...            m3              23.0              8.0                  NaN   

  ikWh_counter1_finish  ikWh_multiplier1  ikWh_unit_name1  ikWh_consumption1  \
0                  NaN               NaN              NaN                NaN   
1                  NaN               NaN              NaN                NaN   
2                  NaN               NaN              NaN                NaN   
3           10922040.0              0,01              kWh               0,69   
4                  NaN               NaN              NaN                NaN   

   ikWh_total_consumption lTriggerCounter  
0                       0             NaN  
1                       0             NaN  
2                       0             NaN  
3                    4,69             NaN  
4                      23             NaN  

[5 rows x 38 columns]

In [16]:
jde_data['LockedByEditor'].unique()

array([nan,  0.])

In [17]:
jde_data[jde_data['LockedByEditor'] == 0.0]

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
7612             1199197  2023-11-30 06:28:11.693        306,8           19   

      IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona SUMA_ZIELONEJ  \
7612      137892        3000          0        NaN         352,6   

      QuantityError  ... im3_unit_name  ikWh_consumption  im3_consumption  \
7612              0  ...            m3              13.0              8.0   

      ikWh_counter1_start ikWh_counter1_finish  ikWh_multiplier1  \
7612                  NaN                  NaN               NaN   

      ikWh_unit_name1  ikWh_consumption1  ikWh_total_consumption  \
7612              NaN                NaN                      13   

     lTriggerCounter  
7612             NaN  

[1 rows x 38 columns]

In [18]:
columns_to_drop.append('LockedByEditor')

In [19]:
jde_data['QuantityError'].unique()

array([1, 0], dtype=int64)

In [20]:
jde_data[jde_data['QuantityError'] == 1]

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0             1206810  2024-01-10 09:06:00.880            0            8   
1             1206809  2024-01-10 08:59:02.527            0            9   
2             1206808  2024-01-10 08:57:40.677            0            7   
3             1206807  2024-01-10 08:49:11.593            0            6   
4             1206806  2024-01-10 08:48:14.330            0            8   
6             1206804  2024-01-10 08:35:09.410            0            5   

   IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona SUMA_ZIELONEJ  QuantityError  \
0      138624        4000          0        NaN             0              1   
1      138623        3000          0        NaN             0              1   
2      138624        4000          0        NaN             0              1   
3      138624        4000          0        NaN         600,1              1   
4      138623        3000          0        NaN         400,3              1   
6      138624        4000          0        NaN         600,2              1   

   ... im3_unit_name  ikWh_consumption  im3_consumption  ikWh_counter1_start  \
0  ...           NaN               NaN              NaN                  NaN   
1  ...           NaN               NaN              NaN                  NaN   
2  ...           NaN               NaN              NaN                  NaN   
3  ...            m3               4.0            474.0           10921971.0   
4  ...            m3              23.0              8.0                  NaN   
6  ...            m3              11.0           1306.0           10921766.0   

  ikWh_counter1_finish  ikWh_multiplier1  ikWh_unit_name1  ikWh_consumption1  \
0                  NaN               NaN              NaN                NaN   
1                  NaN               NaN              NaN                NaN   
2                  NaN               NaN              NaN                NaN   
3           10922040.0              0,01              kWh               0,69   
4                  NaN               NaN              NaN                NaN   
6           10921965.0              0,01              kWh               1,99   

   ikWh_total_consumption lTriggerCounter  
0                       0             NaN  
1                       0             NaN  
2                       0             NaN  
3                    4,69             NaN  
4                      23             NaN  
6                   12,99             NaN  

[6 rows x 38 columns]

In [21]:
columns_to_drop.append('QuantityError')

In [22]:
jde_data['Posted'].unique()

array([0, 1], dtype=int64)

In [23]:
jde_data[jde_data['Posted'] == 0]

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0                1206810  2024-01-10 09:06:00.880            0            8   
1                1206809  2024-01-10 08:59:02.527            0            9   
2                1206808  2024-01-10 08:57:40.677            0            7   
3                1206807  2024-01-10 08:49:11.593            0            6   
4                1206806  2024-01-10 08:48:14.330            0            8   
...                  ...                      ...          ...          ...   
9769             1197040  2023-11-21 05:11:49.350        511,5            4   
9771             1197038  2023-11-21 05:05:09.273        511,9            3   
9802             1197007  2023-11-21 02:28:07.180          300           16   
9886             1196923  2023-11-20 18:08:35.720          299            7   
9943             1196866  2023-11-20 07:55:31.313          501            5   

      IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona SUMA_ZIELONEJ  \
0         138624        4000          0        NaN             0   
1         138623        3000          0        NaN             0   
2         138624        4000          0        NaN             0   
3         138624        4000          0        NaN         600,1   
4         138623        3000          0        NaN         400,3   
...          ...         ...        ...        ...           ...   
9769      137677        4000          0        NaN         600,4   
9771      137677        4000          0        NaN         600,3   
9802      137673        3000          0        NaN         349,2   
9886      137667        3000          0        NaN         348,9   
9943      137660        4000          0        NaN      600,7001   

      QuantityError  ... im3_unit_name  ikWh_consumption  im3_consumption  \
0                 1  ...           NaN               NaN              NaN   
1                 1  ...           NaN               NaN              NaN   
2                 1  ...           NaN               NaN              NaN   
3                 1  ...            m3               4.0            474.0   
4                 1  ...            m3              23.0              8.0   
...             ...  ...           ...               ...              ...   
9769              0  ...            m3              10.0           1311.0   
9771              0  ...            m3               9.0           1322.0   
9802              0  ...            m3              13.0             10.0   
9886              0  ...            m3              14.0             10.0   
9943              0  ...            m3              11.0           1305.0   

      ikWh_counter1_start ikWh_counter1_finish  ikWh_multiplier1  \
0                     NaN                  NaN               NaN   
1                     NaN                  NaN               NaN   
2                     NaN                  NaN               NaN   
3              10921971.0           10922040.0              0,01   
4                     NaN                  NaN               NaN   
...                   ...                  ...               ...   
9769            9773132.0            9773362.0              0,01   
9771            9772900.0            9773073.0              0,01   
9802                  NaN                  NaN               NaN   
9886                  NaN                  NaN               NaN   
9943            9749195.0            9749343.0              0,01   

      ikWh_unit_name1  ikWh_consumption1  ikWh_total_consumption  \
0                 NaN                NaN                       0   
1                 NaN                NaN                       0   
2                 NaN                NaN                       0   
3                 kWh               0,69                    4,69   
4                 NaN                NaN                      23   
...               ...                ...                     ...   
9769              kWh 

In [24]:
columns_to_drop.append('Posted')

In [25]:
columns_to_drop.append('dtLastEdited')

In [26]:
jde_data.head()

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0             1206810  2024-01-10 09:06:00.880            0            8   
1             1206809  2024-01-10 08:59:02.527            0            9   
2             1206808  2024-01-10 08:57:40.677            0            7   
3             1206807  2024-01-10 08:49:11.593            0            6   
4             1206806  2024-01-10 08:48:14.330            0            8   

   IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona SUMA_ZIELONEJ  QuantityError  \
0      138624        4000          0        NaN             0              1   
1      138623        3000          0        NaN             0              1   
2      138624        4000          0        NaN             0              1   
3      138624        4000          0        NaN         600,1              1   
4      138623        3000          0        NaN         400,3              1   

   ... im3_unit_name  ikWh_consumption  im3_consumption  ikWh_counter1_start  \
0  ...           NaN               NaN              NaN                  NaN   
1  ...           NaN               NaN              NaN                  NaN   
2  ...           NaN               NaN              NaN                  NaN   
3  ...            m3               4.0            474.0           10921971.0   
4  ...            m3              23.0              8.0                  NaN   

  ikWh_counter1_finish  ikWh_multiplier1  ikWh_unit_name1  ikWh_consumption1  \
0                  NaN               NaN              NaN                NaN   
1                  NaN               NaN              NaN                NaN   
2                  NaN               NaN              NaN                NaN   
3           10922040.0              0,01              kWh               0,69   
4                  NaN               NaN              NaN                NaN   

   ikWh_total_consumption lTriggerCounter  
0                       0             NaN  
1                       0             NaN  
2                       0             NaN  
3                    4,69             NaN  
4                      23             NaN  

[5 rows x 38 columns]

In [27]:
jde_data['ExternalErrorCleaner'].unique()

array([nan,  1.])

In [28]:
jde_data[jde_data['ExternalErrorCleaner'] == 1]

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
47               1206763  2024-01-10 03:51:05.300        519,3           10   
80               1206730  2024-01-10 01:00:30.273          345           32   
94               1206716  2024-01-09 23:55:07.663        504,6            5   
112              1206698  2024-01-09 22:37:56.997          346           13   
120              1206690  2024-01-09 22:03:15.270          348            9   
...                  ...                      ...          ...          ...   
9888             1196921  2023-11-20 18:01:44.660          310            6   
9890             1196919  2023-11-20 17:51:45.303          310            5   
9917             1196892  2023-11-20 11:20:35.740        427,3            3   
9977             1196832  2023-11-20 04:42:50.003          343            4   
9981             1196828  2023-11-20 04:25:17.787        342,7            2   

      IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona SUMA_ZIELONEJ  \
47        138619        4000          0        NaN         599,7   
80        138612        3000          0        NaN         400,1   
94        138615        4000          0        NaN         598,6   
112       138612        3000          0        NaN         400,2   
120       138612        3000          0        NaN         400,8   
...          ...         ...        ...        ...           ...   
9888      137667        3000          0        NaN         348,9   
9890      137667        3000          0        NaN         349,9   
9917      137662        4000          0        NaN         498,2   
9977      137658        3000          0        NaN         400,2   
9981      137658        3000          0        NaN         399,6   

      QuantityError  ... im3_unit_name  ikWh_consumption  im3_consumption  \
47                0  ...            m3              10.0           1247.0   
80                0  ...            m3              16.0              8.0   
94                0  ...            m3              12.0           1237.0   
112               0  ...            m3              14.0              8.0   
120               0  ...            m3              17.0              9.0   
...             ...  ...           ...               ...              ...   
9888              0  ...            m3              12.0              9.0   
9890              0  ...            m3              12.0              9.0   
9917              0  ...            m3              10.0           1133.0   
9977              0  ...            m3              16.0             10.0   
9981              0  ...            m3              15.0             11.0   

      ikWh_counter1_start ikWh_counter1_finish  ikWh_multiplier1  \
47             10915660.0           10915792.0              0,01   
80                    NaN                  NaN               NaN   
94             10911737.0           10912046.0              0,01   
112                   NaN                  NaN               NaN   
120                   NaN                  NaN               NaN   
...                   ...                  ...               ...   
9888                  NaN                  NaN               NaN   
9890                  NaN                  NaN               NaN   
9917            9752768.0            9752894.0              0,01   
9977                  NaN                  NaN               NaN   
9981                  NaN                  NaN               NaN   

      ikWh_unit_name1  ikWh_consumption1  ikWh_total_consumption  \
47                kWh               1,32                   11,32   
80                NaN                NaN                      16   
94                kWh               3,09                   15,09   
112               NaN                NaN                      14   
120               NaN                NaN                      17   
...               ...                ...                     ...   
9888              NaN 

In [29]:
columns_to_drop.append('ExternalErrorCleaner')

In [30]:
jde_data.head()

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0             1206810  2024-01-10 09:06:00.880            0            8   
1             1206809  2024-01-10 08:59:02.527            0            9   
2             1206808  2024-01-10 08:57:40.677            0            7   
3             1206807  2024-01-10 08:49:11.593            0            6   
4             1206806  2024-01-10 08:48:14.330            0            8   

   IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona SUMA_ZIELONEJ  QuantityError  \
0      138624        4000          0        NaN             0              1   
1      138623        3000          0        NaN             0              1   
2      138624        4000          0        NaN             0              1   
3      138624        4000          0        NaN         600,1              1   
4      138623        3000          0        NaN         400,3              1   

   ... im3_unit_name  ikWh_consumption  im3_consumption  ikWh_counter1_start  \
0  ...           NaN               NaN              NaN                  NaN   
1  ...           NaN               NaN              NaN                  NaN   
2  ...           NaN               NaN              NaN                  NaN   
3  ...            m3               4.0            474.0           10921971.0   
4  ...            m3              23.0              8.0                  NaN   

  ikWh_counter1_finish  ikWh_multiplier1  ikWh_unit_name1  ikWh_consumption1  \
0                  NaN               NaN              NaN                NaN   
1                  NaN               NaN              NaN                NaN   
2                  NaN               NaN              NaN                NaN   
3           10922040.0              0,01              kWh               0,69   
4                  NaN               NaN              NaN                NaN   

   ikWh_total_consumption lTriggerCounter  
0                       0             NaN  
1                       0             NaN  
2                       0             NaN  
3                    4,69             NaN  
4                      23             NaN  

[5 rows x 38 columns]

In [31]:
jde_data['READJUSTED_BY'].unique()

array([nan, 24., 32., 40.,  6., 18., 10.])

In [32]:
columns_to_drop.append('READJUSTED_BY')

In [33]:
jde_data.head()

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0             1206810  2024-01-10 09:06:00.880            0            8   
1             1206809  2024-01-10 08:59:02.527            0            9   
2             1206808  2024-01-10 08:57:40.677            0            7   
3             1206807  2024-01-10 08:49:11.593            0            6   
4             1206806  2024-01-10 08:48:14.330            0            8   

   IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona SUMA_ZIELONEJ  QuantityError  \
0      138624        4000          0        NaN             0              1   
1      138623        3000          0        NaN             0              1   
2      138624        4000          0        NaN             0              1   
3      138624        4000          0        NaN         600,1              1   
4      138623        3000          0        NaN         400,3              1   

   ... im3_unit_name  ikWh_consumption  im3_consumption  ikWh_counter1_start  \
0  ...           NaN               NaN              NaN                  NaN   
1  ...           NaN               NaN              NaN                  NaN   
2  ...           NaN               NaN              NaN                  NaN   
3  ...            m3               4.0            474.0           10921971.0   
4  ...            m3              23.0              8.0                  NaN   

  ikWh_counter1_finish  ikWh_multiplier1  ikWh_unit_name1  ikWh_consumption1  \
0                  NaN               NaN              NaN                NaN   
1                  NaN               NaN              NaN                NaN   
2                  NaN               NaN              NaN                NaN   
3           10922040.0              0,01              kWh               0,69   
4                  NaN               NaN              NaN                NaN   

   ikWh_total_consumption lTriggerCounter  
0                       0             NaN  
1                       0             NaN  
2                       0             NaN  
3                    4,69             NaN  
4                      23             NaN  

[5 rows x 38 columns]

In [34]:
jde_data['TruckNo1'].unique()

array([ nan,   3., 204.,   5.,   7.,   1.,   9.,   8.,   6.,   4.,  10.,
        99., 202., 205.,   2.,  55.,  44.,  88.,  77.,  22., 200.])

In [35]:
columns_to_drop.append('TruckNo1')

In [36]:
jde_data['TruckNo2'].unique()

array([nan])

In [37]:
columns_to_drop.append('TruckNo2')

In [38]:
jde_data.head()

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0             1206810  2024-01-10 09:06:00.880            0            8   
1             1206809  2024-01-10 08:59:02.527            0            9   
2             1206808  2024-01-10 08:57:40.677            0            7   
3             1206807  2024-01-10 08:49:11.593            0            6   
4             1206806  2024-01-10 08:48:14.330            0            8   

   IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona SUMA_ZIELONEJ  QuantityError  \
0      138624        4000          0        NaN             0              1   
1      138623        3000          0        NaN             0              1   
2      138624        4000          0        NaN             0              1   
3      138624        4000          0        NaN         600,1              1   
4      138623        3000          0        NaN         400,3              1   

   ... im3_unit_name  ikWh_consumption  im3_consumption  ikWh_counter1_start  \
0  ...           NaN               NaN              NaN                  NaN   
1  ...           NaN               NaN              NaN                  NaN   
2  ...           NaN               NaN              NaN                  NaN   
3  ...            m3               4.0            474.0           10921971.0   
4  ...            m3              23.0              8.0                  NaN   

  ikWh_counter1_finish  ikWh_multiplier1  ikWh_unit_name1  ikWh_consumption1  \
0                  NaN               NaN              NaN                NaN   
1                  NaN               NaN              NaN                NaN   
2                  NaN               NaN              NaN                NaN   
3           10922040.0              0,01              kWh               0,69   
4                  NaN               NaN              NaN                NaN   

   ikWh_total_consumption lTriggerCounter  
0                       0             NaN  
1                       0             NaN  
2                       0             NaN  
3                    4,69             NaN  
4                      23             NaN  

[5 rows x 38 columns]

In [39]:
jde_data['lTriggerCounter'].unique()

array([  nan,  313.,  311., ..., 7144., 7143., 7142.])

In [40]:
columns_to_drop.append('lTriggerCounter')

In [41]:
jde_data['im3_multiplier'].unique()

array([nan,  1.])

In [42]:
columns_to_drop.append('im3_multiplier')

In [43]:
jde_data['ikWh_multiplier'].unique()

array([nan,  1.])

In [44]:
columns_to_drop.append('ikWh_multiplier')

In [45]:
jde_data['ikWh_unit_name'].unique()

array([nan, 'kWh'], dtype=object)

In [46]:
columns_to_drop.append('ikWh_unit_name')

In [47]:
jde_data['im3_unit_name'].unique()

array([nan, 'm3'], dtype=object)

In [48]:
columns_to_drop.append('im3_unit_name')

In [49]:
jde_data['ikWh_multiplier1'].unique()

array([nan, '0,01'], dtype=object)

In [50]:
columns_to_drop.append('ikWh_multiplier1')  # wrong value in some series

In [51]:
jde_data['ikWh_unit_name1'].unique()

array([nan, 'kWh'], dtype=object)

In [52]:
columns_to_drop.append('ikWh_unit_name1')

In [53]:
jde_data['ikWh_total_consumption'].unique()

array(['0', '4,69', '23', ..., '8,47', '5,72', '9,88'], dtype=object)

In [54]:
jde_data['ikWh_total_consumption'] = jde_data['ikWh_total_consumption'].str.replace(',', '.').astype(float)

In [55]:
jde_data[jde_data['ikWh_total_consumption'] == 0]

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0                1206810  2024-01-10 09:06:00.880            0            8   
1                1206809  2024-01-10 08:59:02.527            0            9   
2                1206808  2024-01-10 08:57:40.677            0            7   
469              1206341  2024-01-08 08:19:50.917            0            5   
1265             1205545  2024-01-03 16:37:02.000            0            1   
2161             1204648  2023-12-27 07:15:29.790          345            4   
2296             1204513  2023-12-22 12:02:09.280          343            3   
2533             1204276  2023-12-21 08:32:02.000            0            1   
3531             1203277  2023-12-17 10:32:50.000            0            1   
3902             1202907  2023-12-15 20:27:59.223          345           23   
8361             1198448  2023-11-26 10:47:31.000            0            1   
8362             1198447  2023-11-26 10:47:17.000            0            1   

      IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona SUMA_ZIELONEJ  \
0         138624        4000          0        NaN             0   
1         138623        3000          0        NaN             0   
2         138624        4000          0        NaN             0   
469       138574        3000          0        NaN             0   
1265      138492        2000          0        NaN           NaN   
2161      138408        3000          0        NaN         400,3   
2296      138395        3000          0        NaN         400,3   
2533      138371        4000          0        NaN           NaN   
3531      138267        4000          0        NaN           NaN   
3902      138229        3000          0        NaN         401,4   
8361      137820        4000          0        NaN           NaN   
8362      137819        4000          0        NaN           NaN   

      QuantityError  ... im3_unit_name  ikWh_consumption  im3_consumption  \
0                 1  ...           NaN               NaN              NaN   
1                 1  ...           NaN               NaN              NaN   
2                 1  ...           NaN               NaN              NaN   
469               0  ...           NaN               NaN              NaN   
1265              0  ...           NaN               NaN              NaN   
2161              0  ...           NaN               NaN              NaN   
2296              0  ...           NaN               NaN              NaN   
2533              0  ...           NaN               NaN              NaN   
3531              0  ...           NaN               NaN              NaN   
3902              0  ...           NaN               NaN              NaN   
8361              0  ...           NaN               NaN              NaN   
8362              0  ...           NaN               NaN              NaN   

      ikWh_counter1_start ikWh_counter1_finish  ikWh_multiplier1  \
0                     NaN                  NaN               NaN   
1                     NaN                  NaN               NaN   
2                     NaN                  NaN               NaN   
469                   NaN                  NaN               NaN   
1265                  NaN                  NaN               NaN   
2161                  NaN                  NaN               NaN   
2296                  NaN                  NaN               NaN   
2533                  NaN                  NaN               NaN   
3531                  NaN                  NaN               NaN   
3902                  NaN                  NaN               NaN   
8361                  NaN                  NaN               NaN   
8362                  NaN                  NaN               NaN   

      ikWh_unit_name1  ikWh_consumption1  ikWh_total_consumption  \
0                 NaN                NaN                     0.0   
1                 NaN                NaN                     0.0   
2 

In [56]:
jde_data.head()

ID_ZLECENIA_PALONA                  DTZAPIS ILOSC_PALONA  NUMERZASYPU  \
0             1206810  2024-01-10 09:06:00.880            0            8   
1             1206809  2024-01-10 08:59:02.527            0            9   
2             1206808  2024-01-10 08:57:40.677            0            7   
3             1206807  2024-01-10 08:49:11.593            0            6   
4             1206806  2024-01-10 08:48:14.330            0            8   

   IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona SUMA_ZIELONEJ  QuantityError  \
0      138624        4000          0        NaN             0              1   
1      138623        3000          0        NaN             0              1   
2      138624        4000          0        NaN             0              1   
3      138624        4000          0        NaN         600,1              1   
4      138623        3000          0        NaN         400,3              1   

   ... im3_unit_name  ikWh_consumption  im3_consumption  ikWh_counter1_start  \
0  ...           NaN               NaN              NaN                  NaN   
1  ...           NaN               NaN              NaN                  NaN   
2  ...           NaN               NaN              NaN                  NaN   
3  ...            m3               4.0            474.0           10921971.0   
4  ...            m3              23.0              8.0                  NaN   

  ikWh_counter1_finish  ikWh_multiplier1  ikWh_unit_name1  ikWh_consumption1  \
0                  NaN               NaN              NaN                NaN   
1                  NaN               NaN              NaN                NaN   
2                  NaN               NaN              NaN                NaN   
3           10922040.0              0,01              kWh               0,69   
4                  NaN               NaN              NaN                NaN   

   ikWh_total_consumption lTriggerCounter  
0                    0.00             NaN  
1                    0.00             NaN  
2                    0.00             NaN  
3                    4.69             NaN  
4                   23.00             NaN  

[5 rows x 38 columns]

In [57]:
jde_data['ikWh_consumption1'] = jde_data['ikWh_consumption1'].str.replace(',', '.').astype(float)

In [58]:
jde_data['DTZAPIS'] = pd.to_datetime(jde_data['DTZAPIS'])

In [59]:
jde_data['ILOSC_PALONA'] = jde_data['ILOSC_PALONA'].str.replace(',', '.').astype(float)

In [60]:
jde_data['SUMA_ZIELONEJ'] = jde_data['SUMA_ZIELONEJ'].str.replace(',', '.').astype(float)

In [61]:
jde_data['PREV_ILOSC_PALONA'] = jde_data['PREV_ILOSC_PALONA'].str.replace(',', '.').astype(float)

In [62]:
jde_data['dtRoastingStart'] = pd.to_datetime(jde_data['dtRoastingStart'])

In [63]:
jde_data['dtRoastingFinish'] = pd.to_datetime(jde_data['dtRoastingFinish'])

In [64]:
jde_data[jde_data['SUMA_ZIELONEJ'].isna()]

ID_ZLECENIA_PALONA             DTZAPIS  ILOSC_PALONA  NUMERZASYPU  \
1265             1205545 2024-01-03 16:37:02           0.0            1   
2533             1204276 2023-12-21 08:32:02           0.0            1   
3531             1203277 2023-12-17 10:32:50           0.0            1   
8361             1198448 2023-11-26 10:47:31           0.0            1   
8362             1198447 2023-11-26 10:47:17           0.0            1   

      IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona  SUMA_ZIELONEJ  \
1265      138492        2000          0        NaN            NaN   
2533      138371        4000          0        NaN            NaN   
3531      138267        4000          0        NaN            NaN   
8361      137820        4000          0        NaN            NaN   
8362      137819        4000          0        NaN            NaN   

      QuantityError  ...  im3_unit_name  ikWh_consumption  im3_consumption  \
1265              0  ...            NaN               NaN              NaN   
2533              0  ...            NaN               NaN              NaN   
3531              0  ...            NaN               NaN              NaN   
8361              0  ...            NaN               NaN              NaN   
8362              0  ...            NaN               NaN              NaN   

      ikWh_counter1_start ikWh_counter1_finish  ikWh_multiplier1  \
1265                  NaN                  NaN               NaN   
2533                  NaN                  NaN               NaN   
3531                  NaN                  NaN               NaN   
8361                  NaN                  NaN               NaN   
8362                  NaN                  NaN               NaN   

      ikWh_unit_name1  ikWh_consumption1  ikWh_total_consumption  \
1265              NaN                NaN                     0.0   
2533              NaN                NaN                     0.0   
3531              NaN                NaN                     0.0   
8361              NaN                NaN                     0.0   
8362              NaN                NaN                     0.0   

     lTriggerCounter  
1265             NaN  
2533             NaN  
3531             NaN  
8361             NaN  
8362             NaN  

[5 rows x 38 columns]

In [65]:
jde_data[jde_data['dtRoastingStart'].isna()]

ID_ZLECENIA_PALONA                 DTZAPIS  ILOSC_PALONA  NUMERZASYPU  \
0                1206810 2024-01-10 09:06:00.880           0.0            8   
1                1206809 2024-01-10 08:59:02.527           0.0            9   
2                1206808 2024-01-10 08:57:40.677           0.0            7   
469              1206341 2024-01-08 08:19:50.917           0.0            5   
1265             1205545 2024-01-03 16:37:02.000           0.0            1   
2161             1204648 2023-12-27 07:15:29.790         345.0            4   
2296             1204513 2023-12-22 12:02:09.280         343.0            3   
2533             1204276 2023-12-21 08:32:02.000           0.0            1   
3531             1203277 2023-12-17 10:32:50.000           0.0            1   
3902             1202907 2023-12-15 20:27:59.223         345.0           23   
8361             1198448 2023-11-26 10:47:31.000           0.0            1   
8362             1198447 2023-11-26 10:47:17.000           0.0            1   

      IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona  SUMA_ZIELONEJ  \
0         138624        4000          0        NaN            0.0   
1         138623        3000          0        NaN            0.0   
2         138624        4000          0        NaN            0.0   
469       138574        3000          0        NaN            0.0   
1265      138492        2000          0        NaN            NaN   
2161      138408        3000          0        NaN          400.3   
2296      138395        3000          0        NaN          400.3   
2533      138371        4000          0        NaN            NaN   
3531      138267        4000          0        NaN            NaN   
3902      138229        3000          0        NaN          401.4   
8361      137820        4000          0        NaN            NaN   
8362      137819        4000          0        NaN            NaN   

      QuantityError  ...  im3_unit_name  ikWh_consumption  im3_consumption  \
0                 1  ...            NaN               NaN              NaN   
1                 1  ...            NaN               NaN              NaN   
2                 1  ...            NaN               NaN              NaN   
469               0  ...            NaN               NaN              NaN   
1265              0  ...            NaN               NaN              NaN   
2161              0  ...            NaN               NaN              NaN   
2296              0  ...            NaN               NaN              NaN   
2533              0  ...            NaN               NaN              NaN   
3531              0  ...            NaN               NaN              NaN   
3902              0  ...            NaN               NaN              NaN   
8361              0  ...            NaN               NaN              NaN   
8362              0  ...            NaN               NaN              NaN   

      ikWh_counter1_start ikWh_counter1_finish  ikWh_multiplier1  \
0                     NaN                  NaN               NaN   
1                     NaN                  NaN               NaN   
2                     NaN                  NaN               NaN   
469                   NaN                  NaN               NaN   
1265                  NaN                  NaN               NaN   
2161                  NaN                  NaN               NaN   
2296                  NaN                  NaN               NaN   
2533                  NaN                  NaN               NaN   
3531                  NaN                  NaN               NaN   
3902                  NaN                  NaN               NaN   
8361                  NaN                  NaN               NaN   
8362                  NaN                  NaN               NaN   

      ikWh_unit_name1  ikWh_consumption1  ikWh_total_consumption  \
0                 NaN                NaN                     0.0   
1                 NaN                NaN    

In [66]:
jde_data

ID_ZLECENIA_PALONA                 DTZAPIS  ILOSC_PALONA  NUMERZASYPU  \
0                1206810 2024-01-10 09:06:00.880           0.0            8   
1                1206809 2024-01-10 08:59:02.527           0.0            9   
2                1206808 2024-01-10 08:57:40.677           0.0            7   
3                1206807 2024-01-10 08:49:11.593           0.0            6   
4                1206806 2024-01-10 08:48:14.330           0.0            8   
...                  ...                     ...           ...          ...   
9995             1196814 2023-11-20 03:12:48.087         251.0           12   
9996             1196813 2023-11-20 03:09:00.397         505.1            7   
9997             1196812 2023-11-20 03:04:52.260         251.9           11   
9998             1196811 2023-11-20 03:00:06.253         505.9            6   
9999             1196810 2023-11-20 02:51:39.743         508.1            5   

      IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona  SUMA_ZIELONEJ  \
0         138624        4000          0        NaN            0.0   
1         138623        3000          0        NaN            0.0   
2         138624        4000          0        NaN            0.0   
3         138624        4000          0        NaN          600.1   
4         138623        3000          0        NaN          400.3   
...          ...         ...        ...        ...            ...   
9995      137655        3000          0        NaN          300.0   
9996      137656        4000          0        NaN          600.1   
9997      137655        3000          0        NaN          291.1   
9998      137656        4000          0        NaN          600.0   
9999      137656        4000          0        NaN          600.2   

      QuantityError  ...  im3_unit_name  ikWh_consumption  im3_consumption  \
0                 1  ...            NaN               NaN              NaN   
1                 1  ...            NaN               NaN              NaN   
2                 1  ...            NaN               NaN              NaN   
3                 1  ...             m3               4.0            474.0   
4                 1  ...             m3              23.0              8.0   
...             ...  ...            ...               ...              ...   
9995              0  ...             m3              13.0              9.0   
9996              0  ...             m3              11.0           1301.0   
9997              0  ...             m3              12.0              9.0   
9998              0  ...             m3              11.0           1307.0   
9999              0  ...             m3              12.0           1292.0   

      ikWh_counter1_start ikWh_counter1_finish  ikWh_multiplier1  \
0                     NaN                  NaN               NaN   
1                     NaN                  NaN               NaN   
2                     NaN                  NaN               NaN   
3              10921971.0           10922040.0              0,01   
4                     NaN                  NaN               NaN   
...                   ...                  ...               ...   
9995                  NaN                  NaN               NaN   
9996            9740934.0            9741095.0              0,01   
9997                  NaN                  NaN               NaN   
9998            9740751.0            9740900.0              0,01   
9999            9740431.0            9740653.0              0,01   

      ikWh_unit_name1  ikWh_consumption1  ikWh_total_consumption  \
0                 NaN                NaN                    0.00   
1                 NaN                NaN                    0.00   
2                 NaN                NaN                    0.00   
3                 kWh               0.69                    4.69   
4                 NaN                NaN                   23.00   
...               ...                ...                     ...  

In [67]:
jde_data = jde_data.dropna(subset=['SUMA_ZIELONEJ'])

In [68]:
jde_data[jde_data['dtRoastingStart'].isna()]

ID_ZLECENIA_PALONA                 DTZAPIS  ILOSC_PALONA  NUMERZASYPU  \
0                1206810 2024-01-10 09:06:00.880           0.0            8   
1                1206809 2024-01-10 08:59:02.527           0.0            9   
2                1206808 2024-01-10 08:57:40.677           0.0            7   
469              1206341 2024-01-08 08:19:50.917           0.0            5   
2161             1204648 2023-12-27 07:15:29.790         345.0            4   
2296             1204513 2023-12-22 12:02:09.280         343.0            3   
3902             1202907 2023-12-15 20:27:59.223         345.0           23   

      IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona  SUMA_ZIELONEJ  \
0         138624        4000          0        NaN            0.0   
1         138623        3000          0        NaN            0.0   
2         138624        4000          0        NaN            0.0   
469       138574        3000          0        NaN            0.0   
2161      138408        3000          0        NaN          400.3   
2296      138395        3000          0        NaN          400.3   
3902      138229        3000          0        NaN          401.4   

      QuantityError  ...  im3_unit_name  ikWh_consumption  im3_consumption  \
0                 1  ...            NaN               NaN              NaN   
1                 1  ...            NaN               NaN              NaN   
2                 1  ...            NaN               NaN              NaN   
469               0  ...            NaN               NaN              NaN   
2161              0  ...            NaN               NaN              NaN   
2296              0  ...            NaN               NaN              NaN   
3902              0  ...            NaN               NaN              NaN   

      ikWh_counter1_start ikWh_counter1_finish  ikWh_multiplier1  \
0                     NaN                  NaN               NaN   
1                     NaN                  NaN               NaN   
2                     NaN                  NaN               NaN   
469                   NaN                  NaN               NaN   
2161                  NaN                  NaN               NaN   
2296                  NaN                  NaN               NaN   
3902                  NaN                  NaN               NaN   

      ikWh_unit_name1  ikWh_consumption1  ikWh_total_consumption  \
0                 NaN                NaN                     0.0   
1                 NaN                NaN                     0.0   
2                 NaN                NaN                     0.0   
469               NaN                NaN                     0.0   
2161              NaN                NaN                     0.0   
2296              NaN                NaN                     0.0   
3902              NaN                NaN                     0.0   

     lTriggerCounter  
0                NaN  
1                NaN  
2                NaN  
469              NaN  
2161             NaN  
2296             NaN  
3902             NaN  

[7 rows x 38 columns]

In [69]:
# jde_data[jde_data['ikWh_multiplier1'] == '0,01']

In [70]:
jde_data.loc[((jde_data['ikWh_counter1_finish'] - jde_data['ikWh_counter1_start']) * .01 != jde_data['ikWh_consumption1'])]

ID_ZLECENIA_PALONA                 DTZAPIS  ILOSC_PALONA  NUMERZASYPU  \
0                1206810 2024-01-10 09:06:00.880           0.0            8   
1                1206809 2024-01-10 08:59:02.527           0.0            9   
2                1206808 2024-01-10 08:57:40.677           0.0            7   
3                1206807 2024-01-10 08:49:11.593           0.0            6   
4                1206806 2024-01-10 08:48:14.330           0.0            8   
...                  ...                     ...           ...          ...   
9992             1196817 2023-11-20 03:30:34.757         250.9           14   
9993             1196816 2023-11-20 03:19:30.917         251.4           13   
9994             1196815 2023-11-20 03:17:40.000         509.7            1   
9995             1196814 2023-11-20 03:12:48.087         251.0           12   
9997             1196812 2023-11-20 03:04:52.260         251.9           11   

      IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona  SUMA_ZIELONEJ  \
0         138624        4000          0        NaN            0.0   
1         138623        3000          0        NaN            0.0   
2         138624        4000          0        NaN            0.0   
3         138624        4000          0        NaN          600.1   
4         138623        3000          0        NaN          400.3   
...          ...         ...        ...        ...            ...   
9992      137655        3000          0        NaN          300.0   
9993      137655        3000          0        NaN          300.0   
9994      137657        4000          0        NaN          600.5   
9995      137655        3000          0        NaN          300.0   
9997      137655        3000          0        NaN          291.1   

      QuantityError  ...  im3_unit_name  ikWh_consumption  im3_consumption  \
0                 1  ...            NaN               NaN              NaN   
1                 1  ...            NaN               NaN              NaN   
2                 1  ...            NaN               NaN              NaN   
3                 1  ...             m3               4.0            474.0   
4                 1  ...             m3              23.0              8.0   
...             ...  ...            ...               ...              ...   
9992              0  ...             m3              12.0              9.0   
9993              0  ...             m3              12.0              9.0   
9994              0  ...             m3              10.0           1353.0   
9995              0  ...             m3              13.0              9.0   
9997              0  ...             m3              12.0              9.0   

      ikWh_counter1_start ikWh_counter1_finish  ikWh_multiplier1  \
0                     NaN                  NaN               NaN   
1                     NaN                  NaN               NaN   
2                     NaN                  NaN               NaN   
3              10921971.0           10922040.0              0,01   
4                     NaN                  NaN               NaN   
...                   ...                  ...               ...   
9992                  NaN                  NaN               NaN   
9993                  NaN                  NaN               NaN   
9994            9741267.0            9741407.0              0,01   
9995                  NaN                  NaN               NaN   
9997                  NaN                  NaN               NaN   

      ikWh_unit_name1  ikWh_consumption1  ikWh_total_consumption  \
0                 NaN                NaN                    0.00   
1                 NaN                NaN                    0.00   
2                 NaN                NaN                    0.00   
3                 kWh               0.69                    4.69   
4                 NaN                NaN                   23.00   
...               ...                ...                     ...  

In [71]:
jde_data.loc[jde_data['ikWh_counter_start'].isna(), 'ikWh_counter1_start'] = 0
jde_data.loc[jde_data['ikWh_counter1_finish'].isna(), 'ikWh_counter1_finish'] = 0
jde_data.loc[jde_data['ikWh_consumption1'].isna(), 'ikWh_consumption1'] = 0

In [72]:
jde_data

ID_ZLECENIA_PALONA                 DTZAPIS  ILOSC_PALONA  NUMERZASYPU  \
0                1206810 2024-01-10 09:06:00.880           0.0            8   
1                1206809 2024-01-10 08:59:02.527           0.0            9   
2                1206808 2024-01-10 08:57:40.677           0.0            7   
3                1206807 2024-01-10 08:49:11.593           0.0            6   
4                1206806 2024-01-10 08:48:14.330           0.0            8   
...                  ...                     ...           ...          ...   
9995             1196814 2023-11-20 03:12:48.087         251.0           12   
9996             1196813 2023-11-20 03:09:00.397         505.1            7   
9997             1196812 2023-11-20 03:04:52.260         251.9           11   
9998             1196811 2023-11-20 03:00:06.253         505.9            6   
9999             1196810 2023-11-20 02:51:39.743         508.1            5   

      IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona  SUMA_ZIELONEJ  \
0         138624        4000          0        NaN            0.0   
1         138623        3000          0        NaN            0.0   
2         138624        4000          0        NaN            0.0   
3         138624        4000          0        NaN          600.1   
4         138623        3000          0        NaN          400.3   
...          ...         ...        ...        ...            ...   
9995      137655        3000          0        NaN          300.0   
9996      137656        4000          0        NaN          600.1   
9997      137655        3000          0        NaN          291.1   
9998      137656        4000          0        NaN          600.0   
9999      137656        4000          0        NaN          600.2   

      QuantityError  ...  im3_unit_name  ikWh_consumption  im3_consumption  \
0                 1  ...            NaN               NaN              NaN   
1                 1  ...            NaN               NaN              NaN   
2                 1  ...            NaN               NaN              NaN   
3                 1  ...             m3               4.0            474.0   
4                 1  ...             m3              23.0              8.0   
...             ...  ...            ...               ...              ...   
9995              0  ...             m3              13.0              9.0   
9996              0  ...             m3              11.0           1301.0   
9997              0  ...             m3              12.0              9.0   
9998              0  ...             m3              11.0           1307.0   
9999              0  ...             m3              12.0           1292.0   

      ikWh_counter1_start ikWh_counter1_finish  ikWh_multiplier1  \
0                     0.0                  0.0               NaN   
1                     0.0                  0.0               NaN   
2                     0.0                  0.0               NaN   
3              10921971.0           10922040.0              0,01   
4                     NaN                  0.0               NaN   
...                   ...                  ...               ...   
9995                  NaN                  0.0               NaN   
9996            9740934.0            9741095.0              0,01   
9997                  NaN                  0.0               NaN   
9998            9740751.0            9740900.0              0,01   
9999            9740431.0            9740653.0              0,01   

      ikWh_unit_name1  ikWh_consumption1  ikWh_total_consumption  \
0                 NaN               0.00                    0.00   
1                 NaN               0.00                    0.00   
2                 NaN               0.00                    0.00   
3                 kWh               0.69                    4.69   
4                 NaN               0.00                   23.00   
...               ...                ...                     ...  

In [74]:
jde_data.loc[:, 'Dlugosc procesu prazenia'] = jde_data['dtRoastingFinish'] - jde_data['dtRoastingStart']

C:\Users\modeb\AppData\Local\Temp\ipykernel_6980\2059104406.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jde_data.loc[:, 'Dlugosc procesu prazenia'] = jde_data['dtRoastingFinish'] - jde_data['dtRoastingStart']


In [75]:
columns_to_drop.append('ikWh_counter_start')
columns_to_drop.append('ikWh_counter_finish')
columns_to_drop.append('im3_counter_start')
columns_to_drop.append('im3_counter_finish')
columns_to_drop.append('ikWh_consumption')
columns_to_drop.append('ikWh_counter1_start')
columns_to_drop.append('ikWh_counter1_finish')
columns_to_drop.append('ikWh_consumption1')

In [76]:
jde_data

ID_ZLECENIA_PALONA                 DTZAPIS  ILOSC_PALONA  NUMERZASYPU  \
0                1206810 2024-01-10 09:06:00.880           0.0            8   
1                1206809 2024-01-10 08:59:02.527           0.0            9   
2                1206808 2024-01-10 08:57:40.677           0.0            7   
3                1206807 2024-01-10 08:49:11.593           0.0            6   
4                1206806 2024-01-10 08:48:14.330           0.0            8   
...                  ...                     ...           ...          ...   
9995             1196814 2023-11-20 03:12:48.087         251.0           12   
9996             1196813 2023-11-20 03:09:00.397         505.1            7   
9997             1196812 2023-11-20 03:04:52.260         251.9           11   
9998             1196811 2023-11-20 03:00:06.253         505.9            6   
9999             1196810 2023-11-20 02:51:39.743         508.1            5   

      IDZLECENIE  NUMERPIECA  Anulowany  Zagubiona  SUMA_ZIELONEJ  \
0         138624        4000          0        NaN            0.0   
1         138623        3000          0        NaN            0.0   
2         138624        4000          0        NaN            0.0   
3         138624        4000          0        NaN          600.1   
4         138623        3000          0        NaN          400.3   
...          ...         ...        ...        ...            ...   
9995      137655        3000          0        NaN          300.0   
9996      137656        4000          0        NaN          600.1   
9997      137655        3000          0        NaN          291.1   
9998      137656        4000          0        NaN          600.0   
9999      137656        4000          0        NaN          600.2   

      QuantityError  ...  ikWh_consumption  im3_consumption  \
0                 1  ...               NaN              NaN   
1                 1  ...               NaN              NaN   
2                 1  ...               NaN              NaN   
3                 1  ...               4.0            474.0   
4                 1  ...              23.0              8.0   
...             ...  ...               ...              ...   
9995              0  ...              13.0              9.0   
9996              0  ...              11.0           1301.0   
9997              0  ...              12.0              9.0   
9998              0  ...              11.0           1307.0   
9999              0  ...              12.0           1292.0   

      ikWh_counter1_start  ikWh_counter1_finish ikWh_multiplier1  \
0                     0.0                   0.0              NaN   
1                     0.0                   0.0              NaN   
2                     0.0                   0.0              NaN   
3              10921971.0            10922040.0             0,01   
4                     NaN                   0.0              NaN   
...                   ...                   ...              ...   
9995                  NaN                   0.0              NaN   
9996            9740934.0             9741095.0             0,01   
9997                  NaN                   0.0              NaN   
9998            9740751.0             9740900.0             0,01   
9999            9740431.0             9740653.0             0,01   

      ikWh_unit_name1  ikWh_consumption1  ikWh_total_consumption  \
0                 NaN               0.00                    0.00   
1                 NaN               0.00                    0.00   
2                 NaN               0.00                    0.00   
3                 kWh               0.69                    4.69   
4                 NaN               0.00                   23.00   
...               ...                ...                     ...   
9995              NaN               0.00                   13.00   
9996              kWh               1.61                   12.61   
9997              NaN               0.00  

In [77]:
jde_data.drop(columns_to_drop, axis=1, inplace=True)

C:\Users\modeb\AppData\Local\Temp\ipykernel_6980\278801080.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jde_data.drop(columns_to_drop, axis=1, inplace=True)


In [78]:
jde_data[jde_data['ikWh_total_consumption'] == 0]

ID_ZLECENIA_PALONA                 DTZAPIS  ILOSC_PALONA  NUMERZASYPU  \
0                1206810 2024-01-10 09:06:00.880           0.0            8   
1                1206809 2024-01-10 08:59:02.527           0.0            9   
2                1206808 2024-01-10 08:57:40.677           0.0            7   
469              1206341 2024-01-08 08:19:50.917           0.0            5   
2161             1204648 2023-12-27 07:15:29.790         345.0            4   
2296             1204513 2023-12-22 12:02:09.280         343.0            3   
3902             1202907 2023-12-15 20:27:59.223         345.0           23   

      IDZLECENIE  NUMERPIECA  SUMA_ZIELONEJ  PREV_ILOSC_PALONA  \
0         138624        4000            0.0                0.0   
1         138623        3000            0.0                0.0   
2         138624        4000            0.0                0.0   
469       138574        3000            0.0                0.0   
2161      138408        3000          400.3              345.0   
2296      138395        3000          400.3              343.0   
3902      138229        3000          401.4              345.0   

      ZbiornikKawyPalonej dtRoastingStart dtRoastingFinish  im3_consumption  \
0                     639             NaT              NaT              NaN   
1                     654             NaT              NaT              NaN   
2                     639             NaT              NaT              NaN   
469                   614             NaT              NaT              NaN   
2161                  613             NaT              NaT              NaN   
2296                  650             NaT              NaT              NaN   
3902                  616             NaT              NaT              NaN   

      ikWh_total_consumption Dlugosc procesu prazenia  
0                        0.0                      NaT  
1                        0.0                      NaT  
2                        0.0                      NaT  
469                      0.0                      NaT  
2161                     0.0                      NaT  
2296                     0.0                      NaT  
3902                     0.0                      NaT

In [79]:
jde_data

ID_ZLECENIA_PALONA                 DTZAPIS  ILOSC_PALONA  NUMERZASYPU  \
0                1206810 2024-01-10 09:06:00.880           0.0            8   
1                1206809 2024-01-10 08:59:02.527           0.0            9   
2                1206808 2024-01-10 08:57:40.677           0.0            7   
3                1206807 2024-01-10 08:49:11.593           0.0            6   
4                1206806 2024-01-10 08:48:14.330           0.0            8   
...                  ...                     ...           ...          ...   
9995             1196814 2023-11-20 03:12:48.087         251.0           12   
9996             1196813 2023-11-20 03:09:00.397         505.1            7   
9997             1196812 2023-11-20 03:04:52.260         251.9           11   
9998             1196811 2023-11-20 03:00:06.253         505.9            6   
9999             1196810 2023-11-20 02:51:39.743         508.1            5   

      IDZLECENIE  NUMERPIECA  SUMA_ZIELONEJ  PREV_ILOSC_PALONA  \
0         138624        4000            0.0                0.0   
1         138623        3000            0.0                0.0   
2         138624        4000            0.0                0.0   
3         138624        4000          600.1                0.0   
4         138623        3000          400.3                0.0   
...          ...         ...            ...                ...   
9995      137655        3000          300.0              251.0   
9996      137656        4000          600.1              505.1   
9997      137655        3000          291.1              251.9   
9998      137656        4000          600.0              505.9   
9999      137656        4000          600.2              508.1   

      ZbiornikKawyPalonej         dtRoastingStart        dtRoastingFinish  \
0                     639                     NaT                     NaT   
1                     654                     NaT                     NaT   
2                     639                     NaT                     NaT   
3                     639 2024-01-10 09:05:27.200 2024-01-10 09:07:42.780   
4                     654 2024-01-10 08:58:30.220 2024-01-10 09:07:42.883   
...                   ...                     ...                     ...   
9995                  625 2023-11-20 03:18:51.253 2023-11-20 03:24:44.123   
9996                  652 2023-11-20 03:32:32.793 2023-11-20 03:40:48.993   
9997                  625 2023-11-20 03:11:40.280 2023-11-20 03:17:20.640   
9998                  652 2023-11-20 03:22:33.460 2023-11-20 03:30:21.983   
9999                  649 2023-11-20 03:08:12.943 2023-11-20 03:16:44.880   

      im3_consumption  ikWh_total_consumption Dlugosc procesu prazenia  
0                 NaN                    0.00                      NaT  
1                 NaN                    0.00                      NaT  
2                 NaN                    0.00                      NaT  
3               474.0                    4.69   0 days 00:02:15.580000  
4                 8.0                   23.00   0 days 00:09:12.663000  
...               ...                     ...                      ...  
9995              9.0                   13.00   0 days 00:05:52.870000  
9996           1301.0                   12.61   0 days 00:08:16.200000  
9997              9.0                   12.00   0 days 00:05:40.360000  
9998           1307.0                   12.49   0 days 00:07:48.523000  
9999           1292.0                   14.22   0 days 00:08:31.937000  

[9995 rows x 14 columns]

In [80]:
jde_data.rename(
    columns={'ID_ZLECENIA_PALONA': 'ID', 'DTZAPIS': 'Data zapisu', 'ILOSC_PALONA': 'Ilosc uprazonej kawy bez strat [kg]',
             'NUMERZASYPU': 'Numer zasypu', 'IDZLECENIE': 'ID zlecenia', 'NUMERPIECA': 'Numer Pieca',
             'SUMA_ZIELONEJ': 'Suma kawy wsypanej na poczatku prazenia [kg]',
             'ZbiornikKawyPalonej': 'Zbiornik kawy palonej', 'im3_consumption' : 'Zuzycie gazu [m3]', 'ikWh_total_consumption' : 'Zuzycie pradu [kWh]', 'dtRoastingStart' : 'Rozpoczecie procesu prazenia', 'dtRoastingFinish' : 'Zakonczenie procesu prazenia' }, inplace=True)

C:\Users\modeb\AppData\Local\Temp\ipykernel_6980\2372222054.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jde_data.rename(


In [81]:
jde_data

ID             Data zapisu  Ilosc uprazonej kawy bez strat [kg]  \
0     1206810 2024-01-10 09:06:00.880                                  0.0   
1     1206809 2024-01-10 08:59:02.527                                  0.0   
2     1206808 2024-01-10 08:57:40.677                                  0.0   
3     1206807 2024-01-10 08:49:11.593                                  0.0   
4     1206806 2024-01-10 08:48:14.330                                  0.0   
...       ...                     ...                                  ...   
9995  1196814 2023-11-20 03:12:48.087                                251.0   
9996  1196813 2023-11-20 03:09:00.397                                505.1   
9997  1196812 2023-11-20 03:04:52.260                                251.9   
9998  1196811 2023-11-20 03:00:06.253                                505.9   
9999  1196810 2023-11-20 02:51:39.743                                508.1   

      Numer zasypu  ID zlecenia  Numer Pieca  \
0                8       138624         4000   
1                9       138623         3000   
2                7       138624         4000   
3                6       138624         4000   
4                8       138623         3000   
...            ...          ...          ...   
9995            12       137655         3000   
9996             7       137656         4000   
9997            11       137655         3000   
9998             6       137656         4000   
9999             5       137656         4000   

      Suma kawy wsypanej na poczatku prazenia [kg]  PREV_ILOSC_PALONA  \
0                                              0.0                0.0   
1                                              0.0                0.0   
2                                              0.0                0.0   
3                                            600.1                0.0   
4                                            400.3                0.0   
...                                            ...                ...   
9995                                         300.0              251.0   
9996                                         600.1              505.1   
9997                                         291.1              251.9   
9998                                         600.0              505.9   
9999                                         600.2              508.1   

      Zbiornik kawy palonej Rozpoczecie procesu prazenia  \
0                       639                          NaT   
1                       654                          NaT   
2                       639                          NaT   
3                       639      2024-01-10 09:05:27.200   
4                       654      2024-01-10 08:58:30.220   
...                     ...                          ...   
9995                    625      2023-11-20 03:18:51.253   
9996                    652      2023-11-20 03:32:32.793   
9997                    625      2023-11-20 03:11:40.280   
9998                    652      2023-11-20 03:22:33.460   
9999                    649      2023-11-20 03:08:12.943   

     Zakonczenie procesu prazenia  Zuzycie gazu [m3]  Zuzycie pradu [kWh]  \
0                             NaT                NaN                 0.00   
1                             NaT                NaN                 0.00   
2                             NaT                NaN                 0.00   
3         2024-01-10 09:07:42.780              474.0                 4.69   
4         2024-01-10 09:07:42.883                8.0                23.00   
...                           ...                ...                  ...   
9995      2023-11-20 03:24:44.123                9.0                13.00   
9996      2023-11-20 03:40:48.993             1301.0                12.61   
9997      2023-11-20 03:17:20.640                9.0                12.00   
9998      2023-11-20 03:30:21.983             1307.0                12.49   
9999      2023-11-20 03:16:44.880             1292.0

In [82]:
jde_data.to_csv('jde_data_cleaned.csv', index=False, sep=';', date_format='%Y-%m-%d %H:%M:%S')